// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef _COMPUTERDASHBOARD_UI_H
#define _COMPUTERDASHBOARD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Home.h"
#include "screens/ui_computerdashboard.h"
#include "screens/ui_ControlPanel.h"
#include "screens/ui_WifiChoose.h"
#include "screens/ui_WifiPwd.h"
#include "screens/ui_BTChoose.h"
#include "screens/ui_Media.h"
#include "screens/ui_About.h"
#include "screens/ui_Weather.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * popkeyboard_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * popoutkeyboard_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * fade_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * pop_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_wifi_0_png);    // assets/wifi/wifi_0.png
LV_IMG_DECLARE(ui_img_1010931293);    // assets/计算机内存卡 (1).png
LV_IMG_DECLARE(ui_img_1793310623);    // assets/硬盘.png
LV_IMG_DECLARE(ui_img_1515518950);    // assets/wifi (1).png
LV_IMG_DECLARE(ui_img_197101833);    // assets/蓝牙 (3).png
LV_IMG_DECLARE(ui_img_1368585089);    // assets/afyaw-oa4gn.png
LV_IMG_DECLARE(ui_img_862951715);    // assets/上一首.png
LV_IMG_DECLARE(ui_img_933793681);    // assets/暂停.png
LV_IMG_DECLARE(ui_img_59290064);    // assets/播放 (1).png
LV_IMG_DECLARE(ui_img_853450402);    // assets/下一首.png
LV_IMG_DECLARE(ui_img_1479610013);    // assets/亮度.png
LV_IMG_DECLARE(ui_img_394312127);    // assets/音量 (1).png
LV_IMG_DECLARE(ui_img_848443434);    // assets/深色模式.png
LV_IMG_DECLARE(ui_img_1479039066);    // assets/文件 (1).png
LV_IMG_DECLARE(ui_img_1978444994);    // assets/自动亮度2 1_lm.png
LV_IMG_DECLARE(ui_img_1934789300);    // assets/关于.png
LV_IMG_DECLARE(ui_img_502970333);    // assets/wifi (6).png
LV_IMG_DECLARE(ui_img_bticon32_png);    // assets/BTIcon32.png

// FONTS
LV_FONT_DECLARE(ui_font_Chinese24);
LV_FONT_DECLARE(ui_font_Font1);
LV_FONT_DECLARE(ui_font_Font150);
LV_FONT_DECLARE(ui_font_Font50);
LV_FONT_DECLARE(ui_font_Font75);
LV_FONT_DECLARE(ui_font_number100);
LV_FONT_DECLARE(ui_font_number150);
LV_FONT_DECLARE(ui_font_Pixel150);
LV_FONT_DECLARE(ui_font_Pixel200);
LV_FONT_DECLARE(ui_font_Pixel2150);
LV_FONT_DECLARE(ui_font_Pixel45);
LV_FONT_DECLARE(ui_font_weatherfont28);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
