// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void ConnectComputer(lv_event_t * e);
void DisconnectComputer(lv_event_t * e);
void LoadInfo(lv_event_t * e);
void wifi_on(lv_event_t * e);
void wifi_off(lv_event_t * e);
void BT_on(lv_event_t * e);
void BT_off(lv_event_t * e);
void LastMusic(lv_event_t * e);
void PauseResume(lv_event_t * e);
void NextMusic(lv_event_t * e);
void ChangeBrightness(lv_event_t * e);
void ChangeVolume(lv_event_t * e);
void Startfileserver(lv_event_t * e);
void Stopfileserver(lv_event_t * e);
void StartAutoBrightness(lv_event_t * e);
void StopAutoBrightness(lv_event_t * e);
void wifi_check(lv_event_t * e);
void wifi_scan(lv_event_t * e);
void WifiConnect1(lv_event_t * e);
void WifiConnect2(lv_event_t * e);
void WifiConnect3(lv_event_t * e);
void WifiConnect4(lv_event_t * e);
void WifiConnect5(lv_event_t * e);
void WifiConnect6(lv_event_t * e);
void WifiConnect7(lv_event_t * e);
void WifiConnect8(lv_event_t * e);
void WifiConnect9(lv_event_t * e);
void ConnectWifi(lv_event_t * e);
void BT_check(lv_event_t * e);
void BT_scan(lv_event_t * e);
void BT_Connect1(lv_event_t * e);
void BT_Connect2(lv_event_t * e);
void BT_Connect3(lv_event_t * e);
void BT_Connect4(lv_event_t * e);
void BT_Connect5(lv_event_t * e);
void BT_Connect6(lv_event_t * e);
void BT_Connect7(lv_event_t * e);
void BT_Connect8(lv_event_t * e);
void BT_Connect9(lv_event_t * e);
void LoadMedia(lv_event_t * e);
void AboutInfo(lv_event_t * e);
void SetComputerIP(lv_event_t * e);
void LoadWeather(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
