// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Text[3] = {0xFFFFFF, 0xFFFFFF, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Text[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Background[3] = {0x000000, 0x000000, 0xDBF7FD};
const ui_theme_variable_t _ui_theme_alpha_Background[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_Highlight[3] = {0x274543, 0x105843, 0xA8D4D1};
const ui_theme_variable_t _ui_theme_alpha_Highlight[3] = {255, 255, 255};

const ui_theme_variable_t _ui_theme_color_BackgroundButtom[3] = {0x4C4C4C, 0x4C4C4C, 0xFFFFFF};
const ui_theme_variable_t _ui_theme_alpha_BackgroundButtom[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_DARK;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

