// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_TEXT 0
#define UI_THEME_COLOR_BACKGROUND 1
#define UI_THEME_COLOR_HIGHLIGHT 2
#define UI_THEME_COLOR_BACKGROUNDBUTTOM 3

#define UI_THEME_DEFAULT 0

#define UI_THEME_DARK 1

#define UI_THEME_LIGHT 2

extern const ui_theme_variable_t _ui_theme_color_Text[3];
extern const ui_theme_variable_t _ui_theme_alpha_Text[3];

extern const ui_theme_variable_t _ui_theme_color_Background[3];
extern const ui_theme_variable_t _ui_theme_alpha_Background[3];

extern const ui_theme_variable_t _ui_theme_color_Highlight[3];
extern const ui_theme_variable_t _ui_theme_alpha_Highlight[3];

extern const ui_theme_variable_t _ui_theme_color_BackgroundButtom[3];
extern const ui_theme_variable_t _ui_theme_alpha_BackgroundButtom[3];

extern const uint32_t * ui_theme_colors[3];
extern const uint8_t * ui_theme_alphas[3];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
