// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_About1;
lv_obj_t * uic_SaveButton;
lv_obj_t * uic_ComputerIParea;
lv_obj_t * uic_ComputerIPLabel;
lv_obj_t * uic_ComputerIP;
lv_obj_t * uic_CheckUpdate;
lv_obj_t * uic_VersionLabel;
lv_obj_t * uic_MACLabel;
lv_obj_t * uic_MAC;
lv_obj_t * uic_DeviceLabel;
lv_obj_t * uic_Device;
lv_obj_t * uic_About;
lv_obj_t * ui_About = NULL;
lv_obj_t * ui_MediaPanel1 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_Device = NULL;
lv_obj_t * ui_DeviceLabel = NULL;
lv_obj_t * ui_MAC = NULL;
lv_obj_t * ui_MACLabel = NULL;
lv_obj_t * ui_Version = NULL;
lv_obj_t * ui_VersionLabel = NULL;
lv_obj_t * ui_CheckUpdate = NULL;
lv_obj_t * ui_ComputerIP = NULL;
lv_obj_t * ui_ComputerIPLabel = NULL;
lv_obj_t * ui_ComputerIParea = NULL;
lv_obj_t * ui_SaveButton = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_About1 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;
// event funtions
void ui_event_About(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        AboutInfo(e);
    }
}

void ui_event_ComputerIParea(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        popkeyboard_Animation(ui_Keyboard2, 0);
        _ui_flag_modify(ui_SaveButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        popoutkeyboard_Animation(ui_Keyboard2, 0);
    }
}

void ui_event_SaveButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_SaveButton, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        SetComputerIP(e);
    }
}

// build funtions

void ui_About_screen_init(void)
{
    ui_About = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_About, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_About, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_About, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_MediaPanel1 = lv_obj_create(ui_About);
    lv_obj_remove_style_all(ui_MediaPanel1);
    lv_obj_set_width(ui_MediaPanel1, lv_pct(80));
    lv_obj_set_height(ui_MediaPanel1, lv_pct(80));
    lv_obj_set_align(ui_MediaPanel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MediaPanel1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel8 = lv_obj_create(ui_MediaPanel1);
    lv_obj_set_width(ui_Panel8, lv_pct(100));
    lv_obj_set_height(ui_Panel8, lv_pct(100));
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel8);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, lv_pct(80));
    lv_obj_set_height(ui_Container8, lv_pct(80));
    lv_obj_set_x(ui_Container8, 4);
    lv_obj_set_y(ui_Container8, 35);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Device = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Device, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Device, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Device, 53);
    lv_obj_set_y(ui_Device, -120);
    lv_obj_set_align(ui_Device, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Device, "Device");
    lv_obj_set_style_text_font(ui_Device, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeviceLabel = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_DeviceLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeviceLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DeviceLabel, 53);
    lv_obj_set_y(ui_DeviceLabel, -120);
    lv_obj_set_align(ui_DeviceLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeviceLabel, "Wave Share 4inch ESP32P4 86Panel");
    lv_obj_set_style_text_font(ui_DeviceLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MAC = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_MAC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MAC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MAC, 55);
    lv_obj_set_y(ui_MAC, -56);
    lv_obj_set_align(ui_MAC, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MAC, "MAC");
    lv_obj_set_style_text_font(ui_MAC, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MACLabel = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_MACLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MACLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MACLabel, 55);
    lv_obj_set_y(ui_MACLabel, -56);
    lv_obj_set_align(ui_MACLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MACLabel, "00:00:00:00:00");
    lv_obj_set_style_text_font(ui_MACLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Version = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_Version, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Version, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Version, 58);
    lv_obj_set_y(ui_Version, 21);
    lv_obj_set_align(ui_Version, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Version, "Version");
    lv_obj_set_style_text_font(ui_Version, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionLabel = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_VersionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VersionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VersionLabel, 58);
    lv_obj_set_y(ui_VersionLabel, 21);
    lv_obj_set_align(ui_VersionLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_VersionLabel, "0.0.0");
    lv_obj_set_style_text_font(ui_VersionLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckUpdate = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_CheckUpdate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckUpdate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckUpdate, 58);
    lv_obj_set_y(ui_CheckUpdate, 21);
    lv_obj_set_align(ui_CheckUpdate, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CheckUpdate, "Check Update");
    lv_obj_add_flag(ui_CheckUpdate, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_CheckUpdate, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ComputerIP = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_ComputerIP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ComputerIP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ComputerIP, 58);
    lv_obj_set_y(ui_ComputerIP, 21);
    lv_obj_set_align(ui_ComputerIP, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ComputerIP, "ComputerIP:");
    lv_obj_set_style_text_font(ui_ComputerIP, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ComputerIPLabel = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_ComputerIPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ComputerIPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ComputerIPLabel, 58);
    lv_obj_set_y(ui_ComputerIPLabel, 21);
    lv_obj_set_align(ui_ComputerIPLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_ComputerIPLabel, "192.168.0.1");
    lv_obj_add_flag(ui_ComputerIPLabel, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_font(ui_ComputerIPLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ComputerIParea = lv_textarea_create(ui_Container8);
    lv_obj_set_width(ui_ComputerIParea, 381);
    lv_obj_set_height(ui_ComputerIParea, LV_SIZE_CONTENT);    /// 49
    lv_obj_set_x(ui_ComputerIParea, -141);
    lv_obj_set_y(ui_ComputerIParea, 85);
    lv_obj_set_align(ui_ComputerIParea, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_ComputerIParea, 20);
    lv_textarea_set_text(ui_ComputerIParea, "192.168.0.1");
    lv_textarea_set_placeholder_text(ui_ComputerIParea, "Enter your computer IP here");
    lv_textarea_set_one_line(ui_ComputerIParea, true);

    ui_SaveButton = lv_button_create(ui_MediaPanel1);
    lv_obj_set_width(ui_SaveButton, 60);
    lv_obj_set_height(ui_SaveButton, 42);
    lv_obj_set_x(ui_SaveButton, -52);
    lv_obj_set_y(ui_SaveButton, 34);
    lv_obj_set_align(ui_SaveButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_SaveButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_SaveButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_SaveButton);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Save");

    ui_About1 = lv_label_create(ui_MediaPanel1);
    lv_obj_set_width(ui_About1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_About1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_About1, 51);
    lv_obj_set_y(ui_About1, -209);
    lv_obj_set_align(ui_About1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_About1, "About");
    lv_obj_set_style_text_font(ui_About1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard2 = lv_keyboard_create(ui_About);
    lv_keyboard_set_mode(ui_Keyboard2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_Keyboard2, lv_pct(100));
    lv_obj_set_height(ui_Keyboard2, lv_pct(40));
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 510);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_ComputerIParea, ui_event_ComputerIParea, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SaveButton, ui_event_SaveButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard2, ui_ComputerIParea);
    lv_obj_add_event_cb(ui_About, ui_event_About, LV_EVENT_ALL, NULL);
    uic_About = ui_About;
    uic_Device = ui_Device;
    uic_DeviceLabel = ui_DeviceLabel;
    uic_MAC = ui_MAC;
    uic_MACLabel = ui_MACLabel;
    uic_VersionLabel = ui_VersionLabel;
    uic_CheckUpdate = ui_CheckUpdate;
    uic_ComputerIP = ui_ComputerIP;
    uic_ComputerIPLabel = ui_ComputerIPLabel;
    uic_ComputerIParea = ui_ComputerIParea;
    uic_SaveButton = ui_SaveButton;
    uic_About1 = ui_About1;

}

void ui_About_screen_destroy(void)
{
    if(ui_About) lv_obj_del(ui_About);

    // NULL screen variables
    uic_About = NULL;
    ui_About = NULL;
    ui_MediaPanel1 = NULL;
    ui_Panel8 = NULL;
    ui_Container8 = NULL;
    uic_Device = NULL;
    ui_Device = NULL;
    uic_DeviceLabel = NULL;
    ui_DeviceLabel = NULL;
    uic_MAC = NULL;
    ui_MAC = NULL;
    uic_MACLabel = NULL;
    ui_MACLabel = NULL;
    ui_Version = NULL;
    uic_VersionLabel = NULL;
    ui_VersionLabel = NULL;
    uic_CheckUpdate = NULL;
    ui_CheckUpdate = NULL;
    uic_ComputerIP = NULL;
    ui_ComputerIP = NULL;
    uic_ComputerIPLabel = NULL;
    ui_ComputerIPLabel = NULL;
    uic_ComputerIParea = NULL;
    ui_ComputerIParea = NULL;
    uic_SaveButton = NULL;
    ui_SaveButton = NULL;
    ui_Label5 = NULL;
    uic_About1 = NULL;
    ui_About1 = NULL;
    ui_Keyboard2 = NULL;

}
