// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_ABOUT_H
#define UI_ABOUT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_About
extern void ui_About_screen_init(void);
extern void ui_About_screen_destroy(void);
extern void ui_event_About(lv_event_t * e);
extern lv_obj_t * ui_About;
extern lv_obj_t * ui_MediaPanel1;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Device;
extern lv_obj_t * ui_DeviceLabel;
extern lv_obj_t * ui_MAC;
extern lv_obj_t * ui_MACLabel;
extern lv_obj_t * ui_Version;
extern lv_obj_t * ui_VersionLabel;
extern lv_obj_t * ui_CheckUpdate;
extern lv_obj_t * ui_ComputerIP;
extern lv_obj_t * ui_ComputerIPLabel;
extern void ui_event_ComputerIParea(lv_event_t * e);
extern lv_obj_t * ui_ComputerIParea;
extern void ui_event_SaveButton(lv_event_t * e);
extern lv_obj_t * ui_SaveButton;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_About1;
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_About;
extern lv_obj_t * uic_Device;
extern lv_obj_t * uic_DeviceLabel;
extern lv_obj_t * uic_MAC;
extern lv_obj_t * uic_MACLabel;
extern lv_obj_t * uic_VersionLabel;
extern lv_obj_t * uic_CheckUpdate;
extern lv_obj_t * uic_ComputerIP;
extern lv_obj_t * uic_ComputerIPLabel;
extern lv_obj_t * uic_ComputerIParea;
extern lv_obj_t * uic_SaveButton;
extern lv_obj_t * uic_About1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

