// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_BTCHOOSE_H
#define UI_BTCHOOSE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BTChoose
extern void ui_BTChoose_screen_init(void);
extern void ui_BTChoose_screen_destroy(void);
extern void ui_event_BTChoose(lv_event_t * e);
extern lv_obj_t * ui_BTChoose;
extern lv_obj_t * ui_WifiGroup2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label1;
extern void ui_event_BTswitch(lv_event_t * e);
extern lv_obj_t * ui_BTswitch;
extern lv_obj_t * ui_BTlist;
extern lv_obj_t * ui_CurrentBT;
extern lv_obj_t * ui_BTIcon32;
extern lv_obj_t * ui_CurrentBTLabel;
extern lv_obj_t * ui_BTStatus;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label3;
extern void ui_event_BTlist1(lv_event_t * e);
extern lv_obj_t * ui_BTlist1;
extern lv_obj_t * ui_BTIcon321;
extern lv_obj_t * ui_BTlistlabel1;
extern lv_obj_t * ui_BTBlock1;
extern void ui_event_BTlist2(lv_event_t * e);
extern lv_obj_t * ui_BTlist2;
extern lv_obj_t * ui_BTIcon1;
extern lv_obj_t * ui_BTlistlabel2;
extern lv_obj_t * ui_BTBlock2;
extern void ui_event_BTlist3(lv_event_t * e);
extern lv_obj_t * ui_BTlist3;
extern lv_obj_t * ui_BTIcon2;
extern lv_obj_t * ui_BTlistlabel3;
extern lv_obj_t * ui_BTBlock3;
extern void ui_event_BTlist4(lv_event_t * e);
extern lv_obj_t * ui_BTlist4;
extern lv_obj_t * ui_BTIcon3;
extern lv_obj_t * ui_BTlistlabel4;
extern lv_obj_t * ui_BTBlock4;
extern void ui_event_BTlist5(lv_event_t * e);
extern lv_obj_t * ui_BTlist5;
extern lv_obj_t * ui_BTIcon4;
extern lv_obj_t * ui_BTlistlabel5;
extern lv_obj_t * ui_BTBlock5;
extern void ui_event_BTlist6(lv_event_t * e);
extern lv_obj_t * ui_BTlist6;
extern lv_obj_t * ui_BTIcon5;
extern lv_obj_t * ui_BTlistlabel6;
extern lv_obj_t * ui_BTBlock6;
extern void ui_event_BTlist7(lv_event_t * e);
extern lv_obj_t * ui_BTlist7;
extern lv_obj_t * ui_BTIcon6;
extern lv_obj_t * ui_BTlistlabel7;
extern lv_obj_t * ui_BTBlock7;
extern void ui_event_BTlist8(lv_event_t * e);
extern lv_obj_t * ui_BTlist8;
extern lv_obj_t * ui_BTIcon7;
extern lv_obj_t * ui_BTlistlabel8;
extern lv_obj_t * ui_BTBlock8;
extern void ui_event_BTlist9(lv_event_t * e);
extern lv_obj_t * ui_BTlist9;
extern lv_obj_t * ui_BTIcon8;
extern lv_obj_t * ui_BTlistlabel9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_BTChoose;
extern lv_obj_t * uic_BTswitch;
extern lv_obj_t * uic_BTlist;
extern lv_obj_t * uic_CurrentBT;
extern lv_obj_t * uic_BTIcon32;
extern lv_obj_t * uic_CurrentBTLabel;
extern lv_obj_t * uic_BTStatus;
extern lv_obj_t * uic_BTlist1;
extern lv_obj_t * uic_BTIcon321;
extern lv_obj_t * uic_BTBlock1;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

