// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_BTBlock1;
lv_obj_t * uic_BTIcon321;
lv_obj_t * uic_BTlist1;
lv_obj_t * uic_BTStatus;
lv_obj_t * uic_CurrentBTLabel;
lv_obj_t * uic_BTIcon32;
lv_obj_t * uic_CurrentBT;
lv_obj_t * uic_BTlist;
lv_obj_t * uic_BTswitch;
lv_obj_t * uic_BTChoose;
lv_obj_t * ui_BTChoose = NULL;
lv_obj_t * ui_WifiGroup2 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_BTswitch = NULL;
lv_obj_t * ui_BTlist = NULL;
lv_obj_t * ui_CurrentBT = NULL;
lv_obj_t * ui_BTIcon32 = NULL;
lv_obj_t * ui_CurrentBTLabel = NULL;
lv_obj_t * ui_BTStatus = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_BTlist1 = NULL;
lv_obj_t * ui_BTIcon321 = NULL;
lv_obj_t * ui_BTlistlabel1 = NULL;
lv_obj_t * ui_BTBlock1 = NULL;
lv_obj_t * ui_BTlist2 = NULL;
lv_obj_t * ui_BTIcon1 = NULL;
lv_obj_t * ui_BTlistlabel2 = NULL;
lv_obj_t * ui_BTBlock2 = NULL;
lv_obj_t * ui_BTlist3 = NULL;
lv_obj_t * ui_BTIcon2 = NULL;
lv_obj_t * ui_BTlistlabel3 = NULL;
lv_obj_t * ui_BTBlock3 = NULL;
lv_obj_t * ui_BTlist4 = NULL;
lv_obj_t * ui_BTIcon3 = NULL;
lv_obj_t * ui_BTlistlabel4 = NULL;
lv_obj_t * ui_BTBlock4 = NULL;
lv_obj_t * ui_BTlist5 = NULL;
lv_obj_t * ui_BTIcon4 = NULL;
lv_obj_t * ui_BTlistlabel5 = NULL;
lv_obj_t * ui_BTBlock5 = NULL;
lv_obj_t * ui_BTlist6 = NULL;
lv_obj_t * ui_BTIcon5 = NULL;
lv_obj_t * ui_BTlistlabel6 = NULL;
lv_obj_t * ui_BTBlock6 = NULL;
lv_obj_t * ui_BTlist7 = NULL;
lv_obj_t * ui_BTIcon6 = NULL;
lv_obj_t * ui_BTlistlabel7 = NULL;
lv_obj_t * ui_BTBlock7 = NULL;
lv_obj_t * ui_BTlist8 = NULL;
lv_obj_t * ui_BTIcon7 = NULL;
lv_obj_t * ui_BTlistlabel8 = NULL;
lv_obj_t * ui_BTBlock8 = NULL;
lv_obj_t * ui_BTlist9 = NULL;
lv_obj_t * ui_BTIcon8 = NULL;
lv_obj_t * ui_BTlistlabel9 = NULL;
// event funtions
void ui_event_BTChoose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        BT_check(e);
    }
}

void ui_event_BTswitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BT_scan(e);
        BT_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BT_off(e);
    }
}

void ui_event_BTlist1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect1(e);
    }
}

void ui_event_BTlist2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect2(e);
    }
}

void ui_event_BTlist3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect3(e);
    }
}

void ui_event_BTlist4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect4(e);
    }
}

void ui_event_BTlist5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect5(e);
    }
}

void ui_event_BTlist6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect6(e);
    }
}

void ui_event_BTlist7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect7(e);
    }
}

void ui_event_BTlist8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect8(e);
    }
}

void ui_event_BTlist9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        BT_Connect9(e);
    }
}

// build funtions

void ui_BTChoose_screen_init(void)
{
    ui_BTChoose = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BTChoose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_BTChoose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_BTChoose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_WifiGroup2 = lv_obj_create(ui_BTChoose);
    lv_obj_remove_style_all(ui_WifiGroup2);
    lv_obj_set_width(ui_WifiGroup2, lv_pct(80));
    lv_obj_set_height(ui_WifiGroup2, lv_pct(80));
    lv_obj_set_align(ui_WifiGroup2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiGroup2, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_WifiGroup2);
    lv_obj_set_width(ui_Panel1, lv_pct(100));
    lv_obj_set_height(ui_Panel1, lv_pct(100));
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 41);
    lv_obj_set_y(ui_Label1, -211);
    lv_obj_set_align(ui_Label1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Label1, "Bluetooth");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTswitch = lv_switch_create(ui_Panel1);
    lv_obj_set_width(ui_BTswitch, 90);
    lv_obj_set_height(ui_BTswitch, 45);
    lv_obj_set_x(ui_BTswitch, 178);
    lv_obj_set_y(ui_BTswitch, -208);
    lv_obj_set_align(ui_BTswitch, LV_ALIGN_CENTER);

    ui_BTlist = lv_obj_create(ui_Panel1);
    lv_obj_remove_style_all(ui_BTlist);
    lv_obj_set_width(ui_BTlist, lv_pct(90));
    lv_obj_set_height(ui_BTlist, lv_pct(73));
    lv_obj_set_x(ui_BTlist, 0);
    lv_obj_set_y(ui_BTlist, 34);
    lv_obj_set_align(ui_BTlist, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BTlist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BTlist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_BTlist, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_CurrentBT = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_CurrentBT, 75);
    lv_obj_set_width(ui_CurrentBT, lv_pct(100));
    lv_obj_set_align(ui_CurrentBT, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_CurrentBT, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CurrentBT, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CurrentBT, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon32 = lv_image_create(ui_CurrentBT);
    lv_image_set_src(ui_BTIcon32, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon32, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon32, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CurrentBTLabel = lv_label_create(ui_CurrentBT);
    lv_obj_set_width(ui_CurrentBTLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CurrentBTLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CurrentBTLabel, 45);
    lv_obj_set_y(ui_CurrentBTLabel, -10);
    lv_obj_set_align(ui_CurrentBTLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_CurrentBTLabel, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_CurrentBTLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTStatus = lv_label_create(ui_CurrentBT);
    lv_obj_set_width(ui_BTStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatus, 47);
    lv_obj_set_y(ui_BTStatus, 11);
    lv_obj_set_align(ui_BTStatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTStatus, "Connected");
    lv_obj_set_style_text_font(ui_BTStatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 100);
    lv_obj_set_height(ui_Container7, 10);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_BTlist);
    lv_obj_set_height(ui_Label3, 30);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label3, 19);
    lv_obj_set_y(ui_Label3, -55);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Avaliable");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTlist1 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist1, 75);
    lv_obj_set_width(ui_BTlist1, lv_pct(100));
    lv_obj_set_align(ui_BTlist1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist1, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon321 = lv_image_create(ui_BTlist1);
    lv_image_set_src(ui_BTIcon321, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon321, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon321, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon321, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon321, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon321, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel1 = lv_label_create(ui_BTlist1);
    lv_obj_set_width(ui_BTlistlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel1, 45);
    lv_obj_set_y(ui_BTlistlabel1, 0);
    lv_obj_set_align(ui_BTlistlabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel1, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock1 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock1);
    lv_obj_set_width(ui_BTBlock1, 100);
    lv_obj_set_height(ui_BTBlock1, 10);
    lv_obj_set_align(ui_BTBlock1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist2 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist2, 75);
    lv_obj_set_width(ui_BTlist2, lv_pct(100));
    lv_obj_set_align(ui_BTlist2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist2, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon1 = lv_image_create(ui_BTlist2);
    lv_image_set_src(ui_BTIcon1, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel2 = lv_label_create(ui_BTlist2);
    lv_obj_set_width(ui_BTlistlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel2, 45);
    lv_obj_set_y(ui_BTlistlabel2, 0);
    lv_obj_set_align(ui_BTlistlabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel2, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock2 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock2);
    lv_obj_set_width(ui_BTBlock2, 100);
    lv_obj_set_height(ui_BTBlock2, 10);
    lv_obj_set_align(ui_BTBlock2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist3 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist3, 75);
    lv_obj_set_width(ui_BTlist3, lv_pct(100));
    lv_obj_set_align(ui_BTlist3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist3, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist3, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon2 = lv_image_create(ui_BTlist3);
    lv_image_set_src(ui_BTIcon2, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel3 = lv_label_create(ui_BTlist3);
    lv_obj_set_width(ui_BTlistlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel3, 45);
    lv_obj_set_y(ui_BTlistlabel3, 0);
    lv_obj_set_align(ui_BTlistlabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel3, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock3 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock3);
    lv_obj_set_width(ui_BTBlock3, 100);
    lv_obj_set_height(ui_BTBlock3, 10);
    lv_obj_set_align(ui_BTBlock3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist4 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist4, 75);
    lv_obj_set_width(ui_BTlist4, lv_pct(100));
    lv_obj_set_align(ui_BTlist4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist4, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist4, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon3 = lv_image_create(ui_BTlist4);
    lv_image_set_src(ui_BTIcon3, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel4 = lv_label_create(ui_BTlist4);
    lv_obj_set_width(ui_BTlistlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel4, 45);
    lv_obj_set_y(ui_BTlistlabel4, 0);
    lv_obj_set_align(ui_BTlistlabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel4, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock4 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock4);
    lv_obj_set_width(ui_BTBlock4, 100);
    lv_obj_set_height(ui_BTBlock4, 10);
    lv_obj_set_align(ui_BTBlock4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist5 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist5, 75);
    lv_obj_set_width(ui_BTlist5, lv_pct(100));
    lv_obj_set_align(ui_BTlist5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist5, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist5, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon4 = lv_image_create(ui_BTlist5);
    lv_image_set_src(ui_BTIcon4, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel5 = lv_label_create(ui_BTlist5);
    lv_obj_set_width(ui_BTlistlabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel5, 45);
    lv_obj_set_y(ui_BTlistlabel5, 0);
    lv_obj_set_align(ui_BTlistlabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel5, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock5 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock5);
    lv_obj_set_width(ui_BTBlock5, 100);
    lv_obj_set_height(ui_BTBlock5, 10);
    lv_obj_set_align(ui_BTBlock5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist6 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist6, 75);
    lv_obj_set_width(ui_BTlist6, lv_pct(100));
    lv_obj_set_align(ui_BTlist6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist6, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist6, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon5 = lv_image_create(ui_BTlist6);
    lv_image_set_src(ui_BTIcon5, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel6 = lv_label_create(ui_BTlist6);
    lv_obj_set_width(ui_BTlistlabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel6, 45);
    lv_obj_set_y(ui_BTlistlabel6, 0);
    lv_obj_set_align(ui_BTlistlabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel6, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock6 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock6);
    lv_obj_set_width(ui_BTBlock6, 100);
    lv_obj_set_height(ui_BTBlock6, 10);
    lv_obj_set_align(ui_BTBlock6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist7 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist7, 75);
    lv_obj_set_width(ui_BTlist7, lv_pct(100));
    lv_obj_set_align(ui_BTlist7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist7, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist7, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon6 = lv_image_create(ui_BTlist7);
    lv_image_set_src(ui_BTIcon6, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon6, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel7 = lv_label_create(ui_BTlist7);
    lv_obj_set_width(ui_BTlistlabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel7, 45);
    lv_obj_set_y(ui_BTlistlabel7, 0);
    lv_obj_set_align(ui_BTlistlabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel7, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock7 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock7);
    lv_obj_set_width(ui_BTBlock7, 100);
    lv_obj_set_height(ui_BTBlock7, 10);
    lv_obj_set_align(ui_BTBlock7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist8 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist8, 75);
    lv_obj_set_width(ui_BTlist8, lv_pct(100));
    lv_obj_set_align(ui_BTlist8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist8, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist8, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon7 = lv_image_create(ui_BTlist8);
    lv_image_set_src(ui_BTIcon7, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon7, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel8 = lv_label_create(ui_BTlist8);
    lv_obj_set_width(ui_BTlistlabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel8, 45);
    lv_obj_set_y(ui_BTlistlabel8, 0);
    lv_obj_set_align(ui_BTlistlabel8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel8, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTBlock8 = lv_obj_create(ui_BTlist);
    lv_obj_remove_style_all(ui_BTBlock8);
    lv_obj_set_width(ui_BTBlock8, 100);
    lv_obj_set_height(ui_BTBlock8, 10);
    lv_obj_set_align(ui_BTBlock8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTBlock8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlist9 = lv_button_create(ui_BTlist);
    lv_obj_set_height(ui_BTlist9, 75);
    lv_obj_set_width(ui_BTlist9, lv_pct(100));
    lv_obj_set_align(ui_BTlist9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_BTlist9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTlist9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTlist9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTlist9, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTlist9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_BTlist9, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon8 = lv_image_create(ui_BTlist9);
    lv_image_set_src(ui_BTIcon8, &ui_img_bticon32_png);
    lv_obj_set_width(ui_BTIcon8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BTIcon8, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTIcon8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BTIcon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BTlistlabel9 = lv_label_create(ui_BTlist9);
    lv_obj_set_width(ui_BTlistlabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTlistlabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTlistlabel9, 45);
    lv_obj_set_y(ui_BTlistlabel9, 0);
    lv_obj_set_align(ui_BTlistlabel9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTlistlabel9, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_BTlistlabel9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BTswitch, ui_event_BTswitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist1, ui_event_BTlist1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist2, ui_event_BTlist2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist3, ui_event_BTlist3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist4, ui_event_BTlist4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist5, ui_event_BTlist5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist6, ui_event_BTlist6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist7, ui_event_BTlist7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist8, ui_event_BTlist8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTlist9, ui_event_BTlist9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTChoose, ui_event_BTChoose, LV_EVENT_ALL, NULL);
    uic_BTChoose = ui_BTChoose;
    uic_BTswitch = ui_BTswitch;
    uic_BTlist = ui_BTlist;
    uic_CurrentBT = ui_CurrentBT;
    uic_BTIcon32 = ui_BTIcon32;
    uic_CurrentBTLabel = ui_CurrentBTLabel;
    uic_BTStatus = ui_BTStatus;
    uic_BTlist1 = ui_BTlist1;
    uic_BTIcon321 = ui_BTIcon321;
    uic_BTBlock1 = ui_BTBlock1;

}

void ui_BTChoose_screen_destroy(void)
{
    if(ui_BTChoose) lv_obj_del(ui_BTChoose);

    // NULL screen variables
    uic_BTChoose = NULL;
    ui_BTChoose = NULL;
    ui_WifiGroup2 = NULL;
    ui_Panel1 = NULL;
    ui_Label1 = NULL;
    uic_BTswitch = NULL;
    ui_BTswitch = NULL;
    uic_BTlist = NULL;
    ui_BTlist = NULL;
    uic_CurrentBT = NULL;
    ui_CurrentBT = NULL;
    uic_BTIcon32 = NULL;
    ui_BTIcon32 = NULL;
    uic_CurrentBTLabel = NULL;
    ui_CurrentBTLabel = NULL;
    uic_BTStatus = NULL;
    ui_BTStatus = NULL;
    ui_Container7 = NULL;
    ui_Label3 = NULL;
    uic_BTlist1 = NULL;
    ui_BTlist1 = NULL;
    uic_BTIcon321 = NULL;
    ui_BTIcon321 = NULL;
    ui_BTlistlabel1 = NULL;
    uic_BTBlock1 = NULL;
    ui_BTBlock1 = NULL;
    ui_BTlist2 = NULL;
    ui_BTIcon1 = NULL;
    ui_BTlistlabel2 = NULL;
    ui_BTBlock2 = NULL;
    ui_BTlist3 = NULL;
    ui_BTIcon2 = NULL;
    ui_BTlistlabel3 = NULL;
    ui_BTBlock3 = NULL;
    ui_BTlist4 = NULL;
    ui_BTIcon3 = NULL;
    ui_BTlistlabel4 = NULL;
    ui_BTBlock4 = NULL;
    ui_BTlist5 = NULL;
    ui_BTIcon4 = NULL;
    ui_BTlistlabel5 = NULL;
    ui_BTBlock5 = NULL;
    ui_BTlist6 = NULL;
    ui_BTIcon5 = NULL;
    ui_BTlistlabel6 = NULL;
    ui_BTBlock6 = NULL;
    ui_BTlist7 = NULL;
    ui_BTIcon6 = NULL;
    ui_BTlistlabel7 = NULL;
    ui_BTBlock7 = NULL;
    ui_BTlist8 = NULL;
    ui_BTIcon7 = NULL;
    ui_BTlistlabel8 = NULL;
    ui_BTBlock8 = NULL;
    ui_BTlist9 = NULL;
    ui_BTIcon8 = NULL;
    ui_BTlistlabel9 = NULL;

}
