// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_COMPUTERDASHBOARD_H
#define UI_COMPUTERDASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_computerdashboard
extern void ui_computerdashboard_screen_init(void);
extern void ui_computerdashboard_screen_destroy(void);
extern void ui_event_computerdashboard(lv_event_t * e);
extern lv_obj_t * ui_computerdashboard;
extern lv_obj_t * ui_Status10;
extern lv_obj_t * ui_TimeButton10;
extern lv_obj_t * ui_Time9;
extern lv_obj_t * ui_Wifi4;
extern lv_obj_t * ui_Content10;
extern lv_obj_t * ui_CPUPanel;
extern lv_obj_t * ui_CPULoad;
extern lv_obj_t * ui_CPULoadLabel;
extern lv_obj_t * ui_CPUName;
extern lv_obj_t * ui_GPUPanel;
extern lv_obj_t * ui_GPULoad;
extern lv_obj_t * ui_GPULoadLabel;
extern lv_obj_t * ui_GPUName;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_RAMPanel;
extern lv_obj_t * ui_RAMIcon;
extern lv_obj_t * ui_RAMLoad;
extern lv_obj_t * ui_RAMLoadLabel;
extern lv_obj_t * ui_DiskPanel;
extern lv_obj_t * ui_DiskIcon;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Disk1Load;
extern lv_obj_t * ui_Disk1Label;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Disk2Load;
extern lv_obj_t * ui_Disk2Label;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Disk3Load;
extern lv_obj_t * ui_Disk3Label;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Disk4Load;
extern lv_obj_t * ui_Disk4Label;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_Disk5Load;
extern lv_obj_t * ui_Disk5Label;
extern lv_obj_t * ui_Container15;
extern lv_obj_t * ui_Disk6Load;
extern lv_obj_t * ui_Disk6Label;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_UploadDownload;
extern lv_obj_t * ui_UploadDownload_Xaxis;
extern lv_obj_t * ui_UploadDownload_Yaxis1;
extern lv_obj_t * ui_UploadDownload_Yaxis2;
extern lv_obj_t * ui_Disk3Load2;
extern lv_obj_t * ui_Disk3Label2;
extern lv_obj_t * ui_UploadLabel;
extern lv_obj_t * ui_DownloadLabel;
extern lv_obj_t * ui_IPLabel;
extern lv_obj_t * ui_loading;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_ComputerStatus;
// CUSTOM VARIABLES
extern lv_obj_t * uic_computerdashboard;
extern lv_obj_t * uic_TimeButton10;
extern lv_obj_t * uic_Time9;
extern lv_obj_t * uic_Wifi4;
extern lv_obj_t * uic_CPUPanel;
extern lv_obj_t * uic_CPULoad;
extern lv_obj_t * uic_CPULoadLabel;
extern lv_obj_t * uic_CPUName;
extern lv_obj_t * uic_GPUPanel;
extern lv_obj_t * uic_GPULoad;
extern lv_obj_t * uic_GPULoadLabel;
extern lv_obj_t * uic_GPUName;
extern lv_obj_t * uic_RAMPanel;
extern lv_obj_t * uic_RAMIcon;
extern lv_obj_t * uic_RAMLoad;
extern lv_obj_t * uic_RAMLoadLabel;
extern lv_obj_t * uic_DiskPanel;
extern lv_obj_t * uic_DiskIcon;
extern lv_obj_t * uic_Disk1Load;
extern lv_obj_t * uic_Disk1Label;
extern lv_obj_t * uic_Disk2Load;
extern lv_obj_t * uic_Disk2Label;
extern lv_obj_t * uic_Disk3Load;
extern lv_obj_t * uic_Disk3Label;
extern lv_obj_t * uic_Disk4Load;
extern lv_obj_t * uic_Disk4Label;
extern lv_obj_t * uic_Disk5Load;
extern lv_obj_t * uic_Disk5Label;
extern lv_obj_t * uic_Disk6Load;
extern lv_obj_t * uic_Disk6Label;
extern lv_obj_t * uic_UploadDownload;
extern lv_obj_t * uic_UploadLabel;
extern lv_obj_t * uic_DownloadLabel;
extern lv_obj_t * uic_IPLabel;
extern lv_obj_t * uic_loading;
extern lv_obj_t * uic_ComputerStatus;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

