// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_CONTROLPANEL_H
#define UI_CONTROLPANEL_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ControlPanel
extern void ui_ControlPanel_screen_init(void);
extern void ui_ControlPanel_screen_destroy(void);
extern void ui_event_ControlPanel(lv_event_t * e);
extern lv_obj_t * ui_ControlPanel;
extern lv_obj_t * ui_Status11;
extern lv_obj_t * ui_TimeButton11;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_ControlGroup;
extern lv_obj_t * ui_Container3;
extern void ui_event_WifiButton(lv_event_t * e);
extern lv_obj_t * ui_WifiButton;
extern lv_obj_t * ui_WifSsidLabel;
extern lv_obj_t * ui_WifiStatusLabel;
extern lv_obj_t * ui_WifiIcon64;
extern void ui_event_BTButton(lv_event_t * e);
extern lv_obj_t * ui_BTButton;
extern lv_obj_t * ui_BTSsidLabel;
extern lv_obj_t * ui_BTStatusLabel;
extern lv_obj_t * ui_BTIcon64;
extern lv_obj_t * ui_Container5;
extern void ui_event_MediaButton(lv_event_t * e);
extern lv_obj_t * ui_MediaButton;
extern lv_obj_t * ui_MediaPlayerLabel;
extern lv_obj_t * ui_MediaPic75;
extern lv_obj_t * ui_MediaName;
extern void ui_event_LastMusic(lv_event_t * e);
extern lv_obj_t * ui_LastMusic;
extern void ui_event_Pause(lv_event_t * e);
extern lv_obj_t * ui_Pause;
extern void ui_event_NextMusic(lv_event_t * e);
extern lv_obj_t * ui_NextMusic;
extern lv_obj_t * ui_Container4;
extern void ui_event_BrightnessSlider(lv_event_t * e);
extern lv_obj_t * ui_BrightnessSlider;
extern lv_obj_t * ui_BrightnessIcon;
extern void ui_event_VolumeSlider(lv_event_t * e);
extern lv_obj_t * ui_VolumeSlider;
extern lv_obj_t * ui_VolumeIcon;
extern lv_obj_t * ui_Container6;
extern void ui_event_StyleButton(lv_event_t * e);
extern lv_obj_t * ui_StyleButton;
extern void ui_event_FileButton(lv_event_t * e);
extern lv_obj_t * ui_FileButton;
extern void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
extern void ui_event_InfoButton(lv_event_t * e);
extern lv_obj_t * ui_InfoButton;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ControlPanel;
extern lv_obj_t * uic_TimeButton11;
extern lv_obj_t * uic_Time;
extern lv_obj_t * uic_ControlGroup;
extern lv_obj_t * uic_WifiButton;
extern lv_obj_t * uic_WifSsidLabel;
extern lv_obj_t * uic_WifiStatusLabel;
extern lv_obj_t * uic_WifiIcon64;
extern lv_obj_t * uic_BTButton;
extern lv_obj_t * uic_BTSsidLabel;
extern lv_obj_t * uic_BTStatusLabel;
extern lv_obj_t * uic_BTIcon64;
extern lv_obj_t * uic_MediaButton;
extern lv_obj_t * uic_MediaPlayerLabel;
extern lv_obj_t * uic_MediaPic75;
extern lv_obj_t * uic_MediaName;
extern lv_obj_t * uic_LastMusic;
extern lv_obj_t * uic_Pause;
extern lv_obj_t * uic_NextMusic;
extern lv_obj_t * uic_Container4;
extern lv_obj_t * uic_BrightnessSlider;
extern lv_obj_t * uic_BrightnessIcon;
extern lv_obj_t * uic_VolumeSlider;
extern lv_obj_t * uic_VolumeIcon;
extern lv_obj_t * uic_StyleButton;
extern lv_obj_t * uic_FileButton;
extern lv_obj_t * uic_InfoButton;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

