// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_ComputerStatus;
lv_obj_t * uic_loading;
lv_obj_t * uic_IPLabel;
lv_obj_t * uic_DownloadLabel;
lv_obj_t * uic_UploadLabel;
lv_obj_t * uic_UploadDownload;
lv_obj_t * uic_Disk6Label;
lv_obj_t * uic_Disk6Load;
lv_obj_t * uic_Disk5Label;
lv_obj_t * uic_Disk5Load;
lv_obj_t * uic_Disk4Label;
lv_obj_t * uic_Disk4Load;
lv_obj_t * uic_Disk3Label;
lv_obj_t * uic_Disk3Load;
lv_obj_t * uic_Disk2Label;
lv_obj_t * uic_Disk2Load;
lv_obj_t * uic_Disk1Label;
lv_obj_t * uic_Disk1Load;
lv_obj_t * uic_DiskIcon;
lv_obj_t * uic_DiskPanel;
lv_obj_t * uic_RAMLoadLabel;
lv_obj_t * uic_RAMLoad;
lv_obj_t * uic_RAMIcon;
lv_obj_t * uic_RAMPanel;
lv_obj_t * uic_GPUName;
lv_obj_t * uic_GPULoadLabel;
lv_obj_t * uic_GPULoad;
lv_obj_t * uic_GPUPanel;
lv_obj_t * uic_CPUName;
lv_obj_t * uic_CPULoadLabel;
lv_obj_t * uic_CPULoad;
lv_obj_t * uic_CPUPanel;
lv_obj_t * uic_Wifi4;
lv_obj_t * uic_Time9;
lv_obj_t * uic_TimeButton10;
lv_obj_t * uic_computerdashboard;
lv_obj_t * ui_computerdashboard = NULL;
lv_obj_t * ui_Status10 = NULL;
lv_obj_t * ui_TimeButton10 = NULL;
lv_obj_t * ui_Time9 = NULL;
lv_obj_t * ui_Wifi4 = NULL;
lv_obj_t * ui_Content10 = NULL;
lv_obj_t * ui_CPUPanel = NULL;
lv_obj_t * ui_CPULoad = NULL;
lv_obj_t * ui_CPULoadLabel = NULL;
lv_obj_t * ui_CPUName = NULL;
lv_obj_t * ui_GPUPanel = NULL;
lv_obj_t * ui_GPULoad = NULL;
lv_obj_t * ui_GPULoadLabel = NULL;
lv_obj_t * ui_GPUName = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_RAMPanel = NULL;
lv_obj_t * ui_RAMIcon = NULL;
lv_obj_t * ui_RAMLoad = NULL;
lv_obj_t * ui_RAMLoadLabel = NULL;
lv_obj_t * ui_DiskPanel = NULL;
lv_obj_t * ui_DiskIcon = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_Disk1Load = NULL;
lv_obj_t * ui_Disk1Label = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_Disk2Load = NULL;
lv_obj_t * ui_Disk2Label = NULL;
lv_obj_t * ui_Container13 = NULL;
lv_obj_t * ui_Disk3Load = NULL;
lv_obj_t * ui_Disk3Label = NULL;
lv_obj_t * ui_Container11 = NULL;
lv_obj_t * ui_Disk4Load = NULL;
lv_obj_t * ui_Disk4Label = NULL;
lv_obj_t * ui_Container14 = NULL;
lv_obj_t * ui_Disk5Load = NULL;
lv_obj_t * ui_Disk5Label = NULL;
lv_obj_t * ui_Container15 = NULL;
lv_obj_t * ui_Disk6Load = NULL;
lv_obj_t * ui_Disk6Label = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_UploadDownload = NULL;
lv_obj_t * ui_UploadDownload_Xaxis = NULL;
lv_obj_t * ui_UploadDownload_Yaxis1 = NULL;
lv_obj_t * ui_UploadDownload_Yaxis2 = NULL;
lv_obj_t * ui_Disk3Load2 = NULL;
lv_obj_t * ui_Disk3Label2 = NULL;
lv_obj_t * ui_UploadLabel = NULL;
lv_obj_t * ui_DownloadLabel = NULL;
lv_obj_t * ui_IPLabel = NULL;
lv_obj_t * ui_loading = NULL;
lv_obj_t * ui_Spinner1 = NULL;
lv_obj_t * ui_ComputerStatus = NULL;
// event funtions
void ui_event_computerdashboard(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        ConnectComputer(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        DisconnectComputer(e);
        _ui_flag_modify(ui_loading, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_computerdashboard_screen_init(void)
{
    ui_computerdashboard = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_computerdashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_computerdashboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_computerdashboard, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Status10 = lv_obj_create(ui_computerdashboard);
    lv_obj_remove_style_all(ui_Status10);
    lv_obj_set_width(ui_Status10, lv_pct(100));
    lv_obj_set_height(ui_Status10, lv_pct(5));
    lv_obj_set_align(ui_Status10, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Status10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Status10, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_Status10, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);

    ui_TimeButton10 = lv_button_create(ui_Status10);
    lv_obj_set_width(ui_TimeButton10, lv_pct(30));
    lv_obj_set_height(ui_TimeButton10, lv_pct(80));
    lv_obj_set_x(ui_TimeButton10, 0);
    lv_obj_set_y(ui_TimeButton10, 3);
    lv_obj_set_align(ui_TimeButton10, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_TimeButton10, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TimeButton10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TimeButton10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_TimeButton10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_outline_color(ui_TimeButton10, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TimeButton10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeButton10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TimeButton10, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_TimeButton10, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeButton10, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_TimeButton10, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);

    ui_Time9 = lv_label_create(ui_TimeButton10);
    lv_obj_set_width(ui_Time9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time9, "--:--");
    ui_object_set_themeable_style_property(ui_Time9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Time9, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_Time9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Time9, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Time9, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifi4 = lv_imagebutton_create(ui_Status10);
    lv_imagebutton_set_src(ui_Wifi4, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_wifi_wifi_0_png, NULL);
    lv_imagebutton_set_src(ui_Wifi4, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_wifi_wifi_0_png, NULL);
    lv_obj_set_width(ui_Wifi4, 32);
    lv_obj_set_height(ui_Wifi4, 32);
    lv_obj_set_x(ui_Wifi4, -7);
    lv_obj_set_y(ui_Wifi4, 1);
    lv_obj_set_align(ui_Wifi4, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_Wifi4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    ui_object_set_themeable_style_property(ui_Wifi4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Wifi4, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_IMAGE_RECOLOR_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_transform_scale(ui_Wifi4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Content10 = lv_obj_create(ui_computerdashboard);
    lv_obj_remove_style_all(ui_Content10);
    lv_obj_set_width(ui_Content10, lv_pct(83));
    lv_obj_set_height(ui_Content10, lv_pct(40));
    lv_obj_set_x(ui_Content10, 0);
    lv_obj_set_y(ui_Content10, 50);
    lv_obj_set_align(ui_Content10, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Content10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Content10, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Content10, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Content10, LV_DIR_VER);

    ui_CPUPanel = lv_obj_create(ui_Content10);
    lv_obj_set_width(ui_CPUPanel, 280);
    lv_obj_set_height(ui_CPUPanel, 280);
    lv_obj_set_align(ui_CPUPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CPUPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CPUPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_CPUPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_CPUPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    lv_obj_set_style_border_width(ui_CPUPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPULoad = lv_arc_create(ui_CPUPanel);
    lv_obj_set_width(ui_CPULoad, 250);
    lv_obj_set_height(ui_CPULoad, 250);
    lv_obj_set_align(ui_CPULoad, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CPULoad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_value(ui_CPULoad, 80);
    lv_obj_set_style_arc_width(ui_CPULoad, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_CPULoad, lv_color_hex(0xF22C51), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_CPULoad, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_CPULoad, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CPULoad, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CPULoad, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_CPULoadLabel = lv_label_create(ui_CPULoad);
    lv_obj_set_width(ui_CPULoadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CPULoadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CPULoadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CPULoadLabel, "--");
    ui_object_set_themeable_style_property(ui_CPULoadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_CPULoadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_CPULoadLabel, &ui_font_Font75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CPUName = lv_label_create(ui_CPUPanel);
    lv_obj_set_width(ui_CPUName, lv_pct(97));
    lv_obj_set_height(ui_CPUName, lv_pct(29));
    lv_obj_set_x(ui_CPUName, 0);
    lv_obj_set_y(ui_CPUName, 130);
    lv_obj_set_align(ui_CPUName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CPUName, "CPU Name Unknown");
    ui_object_set_themeable_style_property(ui_CPUName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_CPUName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_CPUName, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_CPUName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CPUName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPUPanel = lv_obj_create(ui_Content10);
    lv_obj_set_width(ui_GPUPanel, 280);
    lv_obj_set_height(ui_GPUPanel, 280);
    lv_obj_set_x(ui_GPUPanel, 76);
    lv_obj_set_y(ui_GPUPanel, 5);
    lv_obj_set_align(ui_GPUPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GPUPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_GPUPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_GPUPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_GPUPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    lv_obj_set_style_border_width(ui_GPUPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPULoad = lv_arc_create(ui_GPUPanel);
    lv_obj_set_width(ui_GPULoad, 250);
    lv_obj_set_height(ui_GPULoad, 250);
    lv_obj_set_align(ui_GPULoad, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_GPULoad, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK |
                       LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_arc_set_value(ui_GPULoad, 10);
    lv_obj_set_style_arc_width(ui_GPULoad, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_GPULoad, lv_color_hex(0x1ED077), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_GPULoad, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_GPULoad, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_GPULoad, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_GPULoad, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_GPULoadLabel = lv_label_create(ui_GPULoad);
    lv_obj_set_width(ui_GPULoadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_GPULoadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_GPULoadLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPULoadLabel, "--");
    ui_object_set_themeable_style_property(ui_GPULoadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_GPULoadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_GPULoadLabel, &ui_font_Font75, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_GPUName = lv_label_create(ui_GPUPanel);
    lv_obj_set_width(ui_GPUName, lv_pct(97));
    lv_obj_set_height(ui_GPUName, lv_pct(29));
    lv_obj_set_x(ui_GPUName, 4);
    lv_obj_set_y(ui_GPUName, 130);
    lv_obj_set_align(ui_GPUName, LV_ALIGN_CENTER);
    lv_label_set_text(ui_GPUName, "GPU Name Unknown");
    ui_object_set_themeable_style_property(ui_GPUName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_GPUName, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_GPUName, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_GPUName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_GPUName, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_computerdashboard);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(85));
    lv_obj_set_height(ui_Container1, lv_pct(50));
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, -20);
    lv_obj_set_align(ui_Container1, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RAMPanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_RAMPanel, lv_pct(100));
    lv_obj_set_height(ui_RAMPanel, lv_pct(20));
    lv_obj_set_align(ui_RAMPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_RAMPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RAMPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_RAMPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_RAMPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_RAMPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_RAMPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_border_width(ui_RAMPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RAMIcon = lv_image_create(ui_RAMPanel);
    lv_image_set_src(ui_RAMIcon, &ui_img_1010931293);
    lv_obj_set_width(ui_RAMIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RAMIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RAMIcon, -5);
    lv_obj_set_y(ui_RAMIcon, 45);
    lv_obj_set_align(ui_RAMIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_RAMIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_RAMIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_transform_scale(ui_RAMIcon, 70, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RAMLoad = lv_bar_create(ui_RAMPanel);
    lv_obj_set_height(ui_RAMLoad, 20);
    lv_obj_set_width(ui_RAMLoad, lv_pct(85));
    lv_obj_set_x(ui_RAMLoad, -10);
    lv_obj_set_y(ui_RAMLoad, 0);
    lv_obj_set_align(ui_RAMLoad, LV_ALIGN_RIGHT_MID);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_RAMLoad, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_RAMLoad,
                                                                                              lv_obj_get_style_pad_right(ui_RAMLoad, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_RAMLoadLabel = lv_label_create(ui_RAMLoad);
    lv_obj_set_width(ui_RAMLoadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RAMLoadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RAMLoadLabel, 10);
    lv_obj_set_y(ui_RAMLoadLabel, 0);
    lv_obj_set_align(ui_RAMLoadLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_RAMLoadLabel, "--%");
    lv_obj_set_style_text_color(ui_RAMLoadLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RAMLoadLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RAMLoadLabel, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiskPanel = lv_obj_create(ui_Container1);
    lv_obj_set_width(ui_DiskPanel, lv_pct(100));
    lv_obj_set_height(ui_DiskPanel, lv_pct(40));
    lv_obj_set_align(ui_DiskPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_DiskPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DiskPanel, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_DiskPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_DiskPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_DiskPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_DiskPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_border_width(ui_DiskPanel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DiskIcon = lv_image_create(ui_DiskPanel);
    lv_image_set_src(ui_DiskIcon, &ui_img_1793310623);
    lv_obj_set_width(ui_DiskIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DiskIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DiskIcon, -4);
    lv_obj_set_y(ui_DiskIcon, 6);
    lv_obj_set_align(ui_DiskIcon, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DiskIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DiskIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_DiskIcon, 900);
    lv_obj_set_style_transform_scale(ui_DiskIcon, 90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_DiskPanel);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, lv_pct(100));
    lv_obj_set_height(ui_Container9, lv_pct(100));
    lv_obj_set_x(ui_Container9, -10);
    lv_obj_set_y(ui_Container9, 0);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_END);
    lv_obj_add_flag(ui_Container9, LV_OBJ_FLAG_SCROLL_ON_FOCUS | LV_OBJ_FLAG_SCROLL_WITH_ARROW);     /// Flags
    lv_obj_remove_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Disk1Load = lv_bar_create(ui_Container9);
    lv_obj_set_height(ui_Disk1Load, 20);
    lv_obj_set_width(ui_Disk1Load, lv_pct(85));
    lv_obj_set_x(ui_Disk1Load, -10);
    lv_obj_set_y(ui_Disk1Load, 0);
    lv_obj_set_align(ui_Disk1Load, LV_ALIGN_TOP_RIGHT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk1Load, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk1Load,
                                                                                                lv_obj_get_style_pad_right(ui_Disk1Load, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk1Label = lv_label_create(ui_Disk1Load);
    lv_obj_set_width(ui_Disk1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk1Label, 10);
    lv_obj_set_y(ui_Disk1Label, 0);
    lv_obj_set_align(ui_Disk1Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk1Label, "C:--%");
    lv_obj_set_style_text_color(ui_Disk1Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk1Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk1Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 100);
    lv_obj_set_height(ui_Container10, 10);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disk2Load = lv_bar_create(ui_Container9);
    lv_obj_set_height(ui_Disk2Load, 20);
    lv_obj_set_width(ui_Disk2Load, lv_pct(85));
    lv_obj_set_x(ui_Disk2Load, -10);
    lv_obj_set_y(ui_Disk2Load, 0);
    lv_obj_set_align(ui_Disk2Load, LV_ALIGN_RIGHT_MID);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk2Load, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk2Load,
                                                                                                lv_obj_get_style_pad_right(ui_Disk2Load, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk2Label = lv_label_create(ui_Disk2Load);
    lv_obj_set_width(ui_Disk2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk2Label, 10);
    lv_obj_set_y(ui_Disk2Label, 0);
    lv_obj_set_align(ui_Disk2Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk2Label, "D:--%");
    lv_obj_set_style_text_color(ui_Disk2Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk2Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk2Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container13 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 100);
    lv_obj_set_height(ui_Container13, 10);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disk3Load = lv_bar_create(ui_Container9);
    lv_obj_set_height(ui_Disk3Load, 20);
    lv_obj_set_width(ui_Disk3Load, lv_pct(85));
    lv_obj_set_x(ui_Disk3Load, -10);
    lv_obj_set_y(ui_Disk3Load, 0);
    lv_obj_set_align(ui_Disk3Load, LV_ALIGN_BOTTOM_RIGHT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk3Load, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk3Load,
                                                                                                lv_obj_get_style_pad_right(ui_Disk3Load, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk3Label = lv_label_create(ui_Disk3Load);
    lv_obj_set_width(ui_Disk3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk3Label, 10);
    lv_obj_set_y(ui_Disk3Label, 0);
    lv_obj_set_align(ui_Disk3Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk3Label, "E:--%");
    lv_obj_set_style_text_color(ui_Disk3Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk3Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk3Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 100);
    lv_obj_set_height(ui_Container11, 10);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disk4Load = lv_bar_create(ui_Container9);
    lv_obj_set_height(ui_Disk4Load, 20);
    lv_obj_set_width(ui_Disk4Load, lv_pct(85));
    lv_obj_set_x(ui_Disk4Load, -10);
    lv_obj_set_y(ui_Disk4Load, 0);
    lv_obj_set_align(ui_Disk4Load, LV_ALIGN_BOTTOM_RIGHT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk4Load, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk4Load,
                                                                                                lv_obj_get_style_pad_right(ui_Disk4Load, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk4Label = lv_label_create(ui_Disk4Load);
    lv_obj_set_width(ui_Disk4Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk4Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk4Label, 10);
    lv_obj_set_y(ui_Disk4Label, 0);
    lv_obj_set_align(ui_Disk4Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk4Label, "E:--%");
    lv_obj_set_style_text_color(ui_Disk4Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk4Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk4Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 100);
    lv_obj_set_height(ui_Container14, 10);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disk5Load = lv_bar_create(ui_Container9);
    lv_obj_set_height(ui_Disk5Load, 20);
    lv_obj_set_width(ui_Disk5Load, lv_pct(85));
    lv_obj_set_x(ui_Disk5Load, -10);
    lv_obj_set_y(ui_Disk5Load, 0);
    lv_obj_set_align(ui_Disk5Load, LV_ALIGN_BOTTOM_RIGHT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk5Load, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk5Load,
                                                                                                lv_obj_get_style_pad_right(ui_Disk5Load, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk5Label = lv_label_create(ui_Disk5Load);
    lv_obj_set_width(ui_Disk5Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk5Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk5Label, 10);
    lv_obj_set_y(ui_Disk5Label, 0);
    lv_obj_set_align(ui_Disk5Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk5Label, "E:--%");
    lv_obj_set_style_text_color(ui_Disk5Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk5Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk5Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container15 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_Container15);
    lv_obj_set_width(ui_Container15, 100);
    lv_obj_set_height(ui_Container15, 10);
    lv_obj_set_align(ui_Container15, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Disk6Load = lv_bar_create(ui_Container9);
    lv_obj_set_height(ui_Disk6Load, 20);
    lv_obj_set_width(ui_Disk6Load, lv_pct(85));
    lv_obj_set_x(ui_Disk6Load, -10);
    lv_obj_set_y(ui_Disk6Load, 0);
    lv_obj_set_align(ui_Disk6Load, LV_ALIGN_BOTTOM_RIGHT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk6Load, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk6Load,
                                                                                                lv_obj_get_style_pad_right(ui_Disk6Load, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk6Label = lv_label_create(ui_Disk6Load);
    lv_obj_set_width(ui_Disk6Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk6Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk6Label, 10);
    lv_obj_set_y(ui_Disk6Label, 0);
    lv_obj_set_align(ui_Disk6Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk6Label, "E:--%");
    lv_obj_set_style_text_color(ui_Disk6Label, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk6Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk6Label, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, lv_pct(100));
    lv_obj_set_height(ui_Container2, lv_pct(70));
    lv_obj_set_x(ui_Container2, 0);
    lv_obj_set_y(ui_Container2, 9);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UploadDownload = lv_chart_create(ui_Container2);
    lv_obj_set_width(ui_UploadDownload, lv_pct(100));
    lv_obj_set_height(ui_UploadDownload, lv_pct(60));
    lv_obj_set_x(ui_UploadDownload, 99);
    lv_obj_set_y(ui_UploadDownload, 276);
    lv_obj_set_align(ui_UploadDownload, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UploadDownload, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_UploadDownload, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_UploadDownload,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_UploadDownload, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_UploadDownload, LV_CHART_TYPE_LINE);
    lv_chart_set_range(ui_UploadDownload, LV_CHART_AXIS_PRIMARY_Y, 0, 1);
    lv_chart_set_range(ui_UploadDownload, LV_CHART_AXIS_SECONDARY_Y, 0, 0);
    lv_obj_set_style_radius(ui_UploadDownload, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_UploadDownload, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_UploadDownload, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);
    ui_object_set_themeable_style_property(ui_UploadDownload, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_UploadDownload, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_border_width(ui_UploadDownload, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UploadDownload_Xaxis = lv_scale_create(ui_UploadDownload);
    lv_scale_set_mode(ui_UploadDownload_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_UploadDownload_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_UploadDownload_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_UploadDownload_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_UploadDownload,
                                                                           LV_PART_MAIN) + lv_obj_get_style_border_width(ui_UploadDownload, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_UploadDownload_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_UploadDownload_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_UploadDownload_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_UploadDownload_Xaxis, 5, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_UploadDownload_Xaxis, 10, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_UploadDownload_Xaxis, 0, 5 > 0 ? 5 - 1 : 0);
    lv_scale_set_total_tick_count(ui_UploadDownload_Xaxis, (5 > 0 ? 5 - 1 : 0) * 10 + 1);
    lv_scale_set_major_tick_every(ui_UploadDownload_Xaxis, 10 >= 1 ? 10 : 1);
    lv_scale_set_label_show(ui_UploadDownload_Xaxis, false);
    ui_UploadDownload_Yaxis1 = lv_scale_create(ui_UploadDownload);
    lv_scale_set_mode(ui_UploadDownload_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_UploadDownload_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_UploadDownload_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_UploadDownload_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_UploadDownload,
                                                                           LV_PART_MAIN) - lv_obj_get_style_border_width(ui_UploadDownload, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_UploadDownload_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_UploadDownload_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_UploadDownload_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_UploadDownload_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_UploadDownload_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_UploadDownload_Yaxis1,  0, 1);
    lv_scale_set_total_tick_count(ui_UploadDownload_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_UploadDownload_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_UploadDownload_Yaxis1, false);
    ui_UploadDownload_Yaxis2 = lv_scale_create(ui_UploadDownload);
    lv_scale_set_mode(ui_UploadDownload_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_UploadDownload_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_UploadDownload_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_UploadDownload_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_UploadDownload,
                                                                           LV_PART_MAIN) + lv_obj_get_style_border_width(ui_UploadDownload, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_UploadDownload_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_UploadDownload_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_UploadDownload_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_UploadDownload_Yaxis2, 10, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_UploadDownload_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_UploadDownload_Yaxis2,  0, 0);
    lv_scale_set_total_tick_count(ui_UploadDownload_Yaxis2, (10 > 0 ? 10 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_UploadDownload_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_scale_set_label_show(ui_UploadDownload_Yaxis2, false);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_UploadDownload, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_UploadDownload, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_Disk3Load2 = lv_bar_create(ui_Container1);
    lv_obj_set_height(ui_Disk3Load2, 20);
    lv_obj_set_width(ui_Disk3Load2, lv_pct(85));
    lv_obj_set_x(ui_Disk3Load2, -10);
    lv_obj_set_y(ui_Disk3Load2, 0);
    lv_obj_set_align(ui_Disk3Load2, LV_ALIGN_BOTTOM_RIGHT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Disk3Load2, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Disk3Load2,
                                                                                                 lv_obj_get_style_pad_right(ui_Disk3Load2, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_Disk3Label2 = lv_label_create(ui_Disk3Load2);
    lv_obj_set_width(ui_Disk3Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Disk3Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Disk3Label2, 10);
    lv_obj_set_y(ui_Disk3Label2, 0);
    lv_obj_set_align(ui_Disk3Label2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Disk3Label2, "E:--%");
    lv_obj_set_style_text_color(ui_Disk3Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Disk3Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Disk3Label2, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UploadLabel = lv_label_create(ui_computerdashboard);
    lv_obj_set_width(ui_UploadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UploadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UploadLabel, 70);
    lv_obj_set_y(ui_UploadLabel, 217);
    lv_obj_set_align(ui_UploadLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_UploadLabel, "Upload:--MB/s");
    ui_object_set_themeable_style_property(ui_UploadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_UploadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_DownloadLabel = lv_label_create(ui_computerdashboard);
    lv_obj_set_width(ui_DownloadLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DownloadLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DownloadLabel, 70);
    lv_obj_set_y(ui_DownloadLabel, 237);
    lv_obj_set_align(ui_DownloadLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DownloadLabel, "Download:--MB/s");
    ui_object_set_themeable_style_property(ui_DownloadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_DownloadLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_IPLabel = lv_label_create(ui_computerdashboard);
    lv_obj_set_width(ui_IPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPLabel, 70);
    lv_obj_set_y(ui_IPLabel, 257);
    lv_obj_set_align(ui_IPLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_IPLabel, "192.168.0.1");
    ui_object_set_themeable_style_property(ui_IPLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_IPLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);

    ui_loading = lv_obj_create(ui_computerdashboard);
    lv_obj_set_width(ui_loading, lv_pct(100));
    lv_obj_set_height(ui_loading, lv_pct(100));
    lv_obj_set_align(ui_loading, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loading, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_loading, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_loading, lv_color_hex(0x656565), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_loading, 200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_loading);
    //lv_spinner_set_anim_params(ui_Spinner1, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 200);
    lv_obj_set_height(ui_Spinner1, 200);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_Spinner1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner1, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ComputerStatus = lv_label_create(ui_loading);
    lv_obj_set_width(ui_ComputerStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ComputerStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ComputerStatus, 0);
    lv_obj_set_y(ui_ComputerStatus, 163);
    lv_obj_set_align(ui_ComputerStatus, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ComputerStatus, "Connecting to Computer\nPlease wait......");
    lv_obj_set_style_text_font(ui_ComputerStatus, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_computerdashboard, ui_event_computerdashboard, LV_EVENT_ALL, NULL);
    uic_computerdashboard = ui_computerdashboard;
    uic_TimeButton10 = ui_TimeButton10;
    uic_Time9 = ui_Time9;
    uic_Wifi4 = ui_Wifi4;
    uic_CPUPanel = ui_CPUPanel;
    uic_CPULoad = ui_CPULoad;
    uic_CPULoadLabel = ui_CPULoadLabel;
    uic_CPUName = ui_CPUName;
    uic_GPUPanel = ui_GPUPanel;
    uic_GPULoad = ui_GPULoad;
    uic_GPULoadLabel = ui_GPULoadLabel;
    uic_GPUName = ui_GPUName;
    uic_RAMPanel = ui_RAMPanel;
    uic_RAMIcon = ui_RAMIcon;
    uic_RAMLoad = ui_RAMLoad;
    uic_RAMLoadLabel = ui_RAMLoadLabel;
    uic_DiskPanel = ui_DiskPanel;
    uic_DiskIcon = ui_DiskIcon;
    uic_Disk1Load = ui_Disk1Load;
    uic_Disk1Label = ui_Disk1Label;
    uic_Disk2Load = ui_Disk2Load;
    uic_Disk2Label = ui_Disk2Label;
    uic_Disk3Load = ui_Disk3Load;
    uic_Disk3Label = ui_Disk3Label;
    uic_Disk4Load = ui_Disk4Load;
    uic_Disk4Label = ui_Disk4Label;
    uic_Disk5Load = ui_Disk5Load;
    uic_Disk5Label = ui_Disk5Label;
    uic_Disk6Load = ui_Disk6Load;
    uic_Disk6Label = ui_Disk6Label;
    uic_UploadDownload = ui_UploadDownload;
    uic_UploadLabel = ui_UploadLabel;
    uic_DownloadLabel = ui_DownloadLabel;
    uic_IPLabel = ui_IPLabel;
    uic_loading = ui_loading;
    uic_ComputerStatus = ui_ComputerStatus;

}

void ui_computerdashboard_screen_destroy(void)
{
    if(ui_computerdashboard) lv_obj_del(ui_computerdashboard);

    // NULL screen variables
    uic_computerdashboard = NULL;
    ui_computerdashboard = NULL;
    ui_Status10 = NULL;
    uic_TimeButton10 = NULL;
    ui_TimeButton10 = NULL;
    uic_Time9 = NULL;
    ui_Time9 = NULL;
    uic_Wifi4 = NULL;
    ui_Wifi4 = NULL;
    ui_Content10 = NULL;
    uic_CPUPanel = NULL;
    ui_CPUPanel = NULL;
    uic_CPULoad = NULL;
    ui_CPULoad = NULL;
    uic_CPULoadLabel = NULL;
    ui_CPULoadLabel = NULL;
    uic_CPUName = NULL;
    ui_CPUName = NULL;
    uic_GPUPanel = NULL;
    ui_GPUPanel = NULL;
    uic_GPULoad = NULL;
    ui_GPULoad = NULL;
    uic_GPULoadLabel = NULL;
    ui_GPULoadLabel = NULL;
    uic_GPUName = NULL;
    ui_GPUName = NULL;
    ui_Container1 = NULL;
    uic_RAMPanel = NULL;
    ui_RAMPanel = NULL;
    uic_RAMIcon = NULL;
    ui_RAMIcon = NULL;
    uic_RAMLoad = NULL;
    ui_RAMLoad = NULL;
    uic_RAMLoadLabel = NULL;
    ui_RAMLoadLabel = NULL;
    uic_DiskPanel = NULL;
    ui_DiskPanel = NULL;
    uic_DiskIcon = NULL;
    ui_DiskIcon = NULL;
    ui_Container9 = NULL;
    uic_Disk1Load = NULL;
    ui_Disk1Load = NULL;
    uic_Disk1Label = NULL;
    ui_Disk1Label = NULL;
    ui_Container10 = NULL;
    uic_Disk2Load = NULL;
    ui_Disk2Load = NULL;
    uic_Disk2Label = NULL;
    ui_Disk2Label = NULL;
    ui_Container13 = NULL;
    uic_Disk3Load = NULL;
    ui_Disk3Load = NULL;
    uic_Disk3Label = NULL;
    ui_Disk3Label = NULL;
    ui_Container11 = NULL;
    uic_Disk4Load = NULL;
    ui_Disk4Load = NULL;
    uic_Disk4Label = NULL;
    ui_Disk4Label = NULL;
    ui_Container14 = NULL;
    uic_Disk5Load = NULL;
    ui_Disk5Load = NULL;
    uic_Disk5Label = NULL;
    ui_Disk5Label = NULL;
    ui_Container15 = NULL;
    uic_Disk6Load = NULL;
    ui_Disk6Load = NULL;
    uic_Disk6Label = NULL;
    ui_Disk6Label = NULL;
    ui_Container2 = NULL;
    uic_UploadDownload = NULL;
    ui_UploadDownload = NULL;
    ui_Disk3Load2 = NULL;
    ui_Disk3Label2 = NULL;
    uic_UploadLabel = NULL;
    ui_UploadLabel = NULL;
    uic_DownloadLabel = NULL;
    ui_DownloadLabel = NULL;
    uic_IPLabel = NULL;
    ui_IPLabel = NULL;
    uic_loading = NULL;
    ui_loading = NULL;
    ui_Spinner1 = NULL;
    uic_ComputerStatus = NULL;
    ui_ComputerStatus = NULL;

}
