// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_InfoButton;
lv_obj_t * uic_FileButton;
lv_obj_t * uic_StyleButton;
lv_obj_t * uic_VolumeIcon;
lv_obj_t * uic_VolumeSlider;
lv_obj_t * uic_BrightnessIcon;
lv_obj_t * uic_BrightnessSlider;
lv_obj_t * uic_Container4;
lv_obj_t * uic_NextMusic;
lv_obj_t * uic_Pause;
lv_obj_t * uic_LastMusic;
lv_obj_t * uic_MediaName;
lv_obj_t * uic_MediaPic75;
lv_obj_t * uic_MediaPlayerLabel;
lv_obj_t * uic_MediaButton;
lv_obj_t * uic_BTIcon64;
lv_obj_t * uic_BTStatusLabel;
lv_obj_t * uic_BTSsidLabel;
lv_obj_t * uic_BTButton;
lv_obj_t * uic_WifiIcon64;
lv_obj_t * uic_WifiStatusLabel;
lv_obj_t * uic_WifSsidLabel;
lv_obj_t * uic_WifiButton;
lv_obj_t * uic_ControlGroup;
lv_obj_t * uic_Time;
lv_obj_t * uic_TimeButton11;
lv_obj_t * uic_ControlPanel;
lv_obj_t * ui_ControlPanel = NULL;
lv_obj_t * ui_Status11 = NULL;
lv_obj_t * ui_TimeButton11 = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_ControlGroup = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_WifiButton = NULL;
lv_obj_t * ui_WifSsidLabel = NULL;
lv_obj_t * ui_WifiStatusLabel = NULL;
lv_obj_t * ui_WifiIcon64 = NULL;
lv_obj_t * ui_BTButton = NULL;
lv_obj_t * ui_BTSsidLabel = NULL;
lv_obj_t * ui_BTStatusLabel = NULL;
lv_obj_t * ui_BTIcon64 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_MediaButton = NULL;
lv_obj_t * ui_MediaPlayerLabel = NULL;
lv_obj_t * ui_MediaPic75 = NULL;
lv_obj_t * ui_MediaName = NULL;
lv_obj_t * ui_LastMusic = NULL;
lv_obj_t * ui_Pause = NULL;
lv_obj_t * ui_NextMusic = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_BrightnessSlider = NULL;
lv_obj_t * ui_BrightnessIcon = NULL;
lv_obj_t * ui_VolumeSlider = NULL;
lv_obj_t * ui_VolumeIcon = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_StyleButton = NULL;
lv_obj_t * ui_FileButton = NULL;
lv_obj_t * ui_Button15 = NULL;
lv_obj_t * ui_InfoButton = NULL;
// event funtions
void ui_event_ControlPanel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadInfo(e);
    }
}

void ui_event_WifiButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_WifiChoose, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiChoose_screen_init);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        wifi_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        wifi_off(e);
    }
}

void ui_event_BTButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_BTChoose, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_BTChoose_screen_init);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BT_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        BT_off(e);
    }
}

void ui_event_MediaButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Media, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Media_screen_init);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        _ui_screen_change(&ui_Media, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_Media_screen_init);
    }
}

void ui_event_LastMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LastMusic(e);
    }
}

void ui_event_Pause(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PauseResume(e);
    }
}

void ui_event_NextMusic(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextMusic(e);
    }
}

void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeBrightness(e);
    }
}

void ui_event_VolumeSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        ChangeVolume(e);
    }
}

void ui_event_StyleButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_DARK);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_switch_theme(UI_THEME_LIGHT);
    }
}

void ui_event_FileButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Startfileserver(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        Stopfileserver(e);
    }
}

void ui_event_Button15(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        StartAutoBrightness(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        StopAutoBrightness(e);
    }
}

void ui_event_InfoButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_About, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_About_screen_init);
    }
}

// build funtions

void ui_ControlPanel_screen_init(void)
{
    ui_ControlPanel = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ControlPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_ControlPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_ControlPanel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Status11 = lv_obj_create(ui_ControlPanel);
    lv_obj_remove_style_all(ui_Status11);
    lv_obj_set_width(ui_Status11, lv_pct(100));
    lv_obj_set_height(ui_Status11, lv_pct(5));
    lv_obj_set_align(ui_Status11, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Status11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Status11, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_Status11, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);

    ui_TimeButton11 = lv_button_create(ui_Status11);
    lv_obj_set_width(ui_TimeButton11, lv_pct(30));
    lv_obj_set_height(ui_TimeButton11, lv_pct(80));
    lv_obj_set_x(ui_TimeButton11, 0);
    lv_obj_set_y(ui_TimeButton11, 3);
    lv_obj_set_align(ui_TimeButton11, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_TimeButton11, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TimeButton11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_TimeButton11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TimeButton11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_TimeButton11, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TimeButton11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeButton11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TimeButton11, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_TimeButton11, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeButton11, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_TimeButton11, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);

    ui_Time = lv_label_create(ui_TimeButton11);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "--:--");
    ui_object_set_themeable_style_property(ui_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Time, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_Time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Time, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Time, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ControlGroup = lv_obj_create(ui_ControlPanel);
    lv_obj_remove_style_all(ui_ControlGroup);
    lv_obj_set_width(ui_ControlGroup, lv_pct(88));
    lv_obj_set_height(ui_ControlGroup, lv_pct(93));
    lv_obj_set_x(ui_ControlGroup, 0);
    lv_obj_set_y(ui_ControlGroup, 20);
    lv_obj_set_align(ui_ControlGroup, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ControlGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scroll_dir(ui_ControlGroup, LV_DIR_VER);

    ui_Container3 = lv_obj_create(ui_ControlGroup);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_height(ui_Container3, 150);
    lv_obj_set_width(ui_Container3, lv_pct(100));
    lv_obj_set_x(ui_Container3, 0);
    lv_obj_set_y(ui_Container3, -1);
    lv_obj_set_align(ui_Container3, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WifiButton = lv_button_create(ui_Container3);
    lv_obj_set_height(ui_WifiButton, 138);
    lv_obj_set_width(ui_WifiButton, lv_pct(46));
    lv_obj_set_align(ui_WifiButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_WifiButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_WifiButton, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WifiButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiButton, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WifiButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_WifiButton, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_WifiButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_WifSsidLabel = lv_label_create(ui_WifiButton);
    lv_obj_set_width(ui_WifSsidLabel, lv_pct(80));
    lv_obj_set_height(ui_WifSsidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifSsidLabel, 70);
    lv_obj_set_y(ui_WifSsidLabel, -12);
    lv_obj_set_align(ui_WifSsidLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_WifSsidLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_WifSsidLabel, "WLAN");
    lv_obj_remove_flag(ui_WifSsidLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_WifSsidLabel, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_text_letter_space(ui_WifSsidLabel, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WifSsidLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WifSsidLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiStatusLabel = lv_label_create(ui_WifiButton);
    lv_obj_set_width(ui_WifiStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiStatusLabel, 71);
    lv_obj_set_y(ui_WifiStatusLabel, 19);
    lv_obj_set_align(ui_WifiStatusLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WifiStatusLabel, "disconnected");
    lv_obj_remove_flag(ui_WifiStatusLabel,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);     /// Flags
    lv_obj_set_style_text_font(ui_WifiStatusLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon64 = lv_image_create(ui_WifiButton);
    lv_image_set_src(ui_WifiIcon64, &ui_img_1515518950);
    lv_obj_set_width(ui_WifiIcon64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiIcon64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WifiIcon64, -90);
    lv_obj_set_y(ui_WifiIcon64, 0);
    lv_obj_set_align(ui_WifiIcon64, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiIcon64, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_BTButton = lv_button_create(ui_Container3);
    lv_obj_set_height(ui_BTButton, 138);
    lv_obj_set_width(ui_BTButton, lv_pct(46));
    lv_obj_set_align(ui_BTButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_BTButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BTButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BTButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTButton, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BTButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BTButton, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_BTButton, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_BTSsidLabel = lv_label_create(ui_BTButton);
    lv_obj_set_width(ui_BTSsidLabel, lv_pct(80));
    lv_obj_set_height(ui_BTSsidLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTSsidLabel, 70);
    lv_obj_set_y(ui_BTSsidLabel, -12);
    lv_obj_set_align(ui_BTSsidLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_BTSsidLabel, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_BTSsidLabel, "Bluetooth");
    lv_obj_remove_flag(ui_BTSsidLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_scrollbar_mode(ui_BTSsidLabel, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_style_text_letter_space(ui_BTSsidLabel, -2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_BTSsidLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BTSsidLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTStatusLabel = lv_label_create(ui_BTButton);
    lv_obj_set_width(ui_BTStatusLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTStatusLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTStatusLabel, 71);
    lv_obj_set_y(ui_BTStatusLabel, 19);
    lv_obj_set_align(ui_BTStatusLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_BTStatusLabel, "unsupported");
    lv_obj_remove_flag(ui_BTStatusLabel,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);    /// Flags
    lv_obj_set_style_text_font(ui_BTStatusLabel, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BTIcon64 = lv_image_create(ui_BTButton);
    lv_image_set_src(ui_BTIcon64, &ui_img_197101833);
    lv_obj_set_width(ui_BTIcon64, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BTIcon64, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BTIcon64, -90);
    lv_obj_set_y(ui_BTIcon64, 0);
    lv_obj_set_align(ui_BTIcon64, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BTIcon64, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_Container5 = lv_obj_create(ui_ControlGroup);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_height(ui_Container5, 312);
    lv_obj_set_width(ui_Container5, lv_pct(100));
    lv_obj_set_x(ui_Container5, 0);
    lv_obj_set_y(ui_Container5, 190);
    lv_obj_set_align(ui_Container5, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MediaButton = lv_button_create(ui_Container5);
    lv_obj_set_width(ui_MediaButton, 284);
    lv_obj_set_height(ui_MediaButton, 284);
    lv_obj_set_x(ui_MediaButton, 4);
    lv_obj_set_y(ui_MediaButton, 0);
    lv_obj_add_flag(ui_MediaButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_MediaButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MediaButton, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MediaButton, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MediaButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MediaPlayerLabel = lv_label_create(ui_MediaButton);
    lv_obj_set_width(ui_MediaPlayerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediaPlayerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediaPlayerLabel, 15);
    lv_obj_set_y(ui_MediaPlayerLabel, 20);
    lv_obj_set_align(ui_MediaPlayerLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_MediaPlayerLabel, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_MediaPlayerLabel, "还给我神ID");

    ui_MediaPic75 = lv_image_create(ui_MediaButton);
    lv_image_set_src(ui_MediaPic75, &ui_img_1368585089);
    lv_obj_set_width(ui_MediaPic75, 64);
    lv_obj_set_height(ui_MediaPic75, 64);
    lv_obj_set_x(ui_MediaPic75, 14);
    lv_obj_set_y(ui_MediaPic75, -78);
    lv_obj_set_align(ui_MediaPic75, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_MediaPic75, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_MediaPic75, 150);

    ui_MediaName = lv_label_create(ui_MediaButton);
    lv_obj_set_width(ui_MediaName, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediaName, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediaName, 14);
    lv_obj_set_y(ui_MediaName, -10);
    lv_obj_set_align(ui_MediaName, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(ui_MediaName, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_MediaName, "Normal No More(哈基米_");
    lv_obj_remove_flag(ui_MediaName, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_font(ui_MediaName, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastMusic = lv_imagebutton_create(ui_MediaButton);
    lv_imagebutton_set_src(ui_LastMusic, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_862951715, NULL);
    lv_imagebutton_set_src(ui_LastMusic, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_862951715, NULL);
    lv_obj_set_width(ui_LastMusic, 48);
    lv_obj_set_height(ui_LastMusic, 48);
    lv_obj_set_x(ui_LastMusic, 10);
    lv_obj_set_y(ui_LastMusic, -15);
    lv_obj_set_align(ui_LastMusic, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_transform_scale(ui_LastMusic, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_LastMusic, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_LastMusic, 30, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Pause = lv_imagebutton_create(ui_MediaButton);
    lv_imagebutton_set_src(ui_Pause, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_933793681, NULL);
    lv_imagebutton_set_src(ui_Pause, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_933793681, NULL);
    lv_imagebutton_set_src(ui_Pause, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_59290064, NULL);
    lv_imagebutton_set_src(ui_Pause, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_59290064, NULL);
    lv_obj_set_width(ui_Pause, 48);
    lv_obj_set_height(ui_Pause, 48);
    lv_obj_set_x(ui_Pause, 2);
    lv_obj_set_y(ui_Pause, -15);
    lv_obj_set_align(ui_Pause, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Pause, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_transform_scale(ui_Pause, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_Pause, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_Pause, 30, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_NextMusic = lv_imagebutton_create(ui_MediaButton);
    lv_imagebutton_set_src(ui_NextMusic, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_853450402, NULL);
    lv_imagebutton_set_src(ui_NextMusic, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_853450402, NULL);
    lv_obj_set_width(ui_NextMusic, 48);
    lv_obj_set_height(ui_NextMusic, 48);
    lv_obj_set_x(ui_NextMusic, -5);
    lv_obj_set_y(ui_NextMusic, -15);
    lv_obj_set_align(ui_NextMusic, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_set_style_transform_scale(ui_NextMusic, 280, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_x(ui_NextMusic, 30, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_transform_pivot_y(ui_NextMusic, 30, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Container4 = lv_obj_create(ui_Container5);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 284);
    lv_obj_set_height(ui_Container4, 286);
    lv_obj_set_x(ui_Container4, -3);
    lv_obj_set_y(ui_Container4, 0);
    lv_obj_set_align(ui_Container4, LV_ALIGN_TOP_RIGHT);
    lv_obj_remove_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_BrightnessSlider = lv_slider_create(ui_Container4);
    lv_slider_set_value(ui_BrightnessSlider, 70, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 100,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_BrightnessSlider, 120);
    lv_obj_set_height(ui_BrightnessSlider, 284);
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_LEFT_MID);
    lv_obj_remove_flag(ui_BrightnessSlider,
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_radius(ui_BrightnessSlider, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_BrightnessSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_BrightnessSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BrightnessSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_BrightnessSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_BrightnessSlider,
                                                                                                       lv_obj_get_style_pad_right(ui_BrightnessSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BrightnessIcon = lv_image_create(ui_BrightnessSlider);
    lv_image_set_src(ui_BrightnessIcon, &ui_img_1479610013);
    lv_obj_set_width(ui_BrightnessIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessIcon, 0);
    lv_obj_set_y(ui_BrightnessIcon, 90);
    lv_obj_set_align(ui_BrightnessIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BrightnessIcon,
                       LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLLABLE);     /// Flags

    ui_VolumeSlider = lv_slider_create(ui_Container4);
    lv_slider_set_value(ui_VolumeSlider, 30, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_VolumeSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_VolumeSlider, 100,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_VolumeSlider, 120);
    lv_obj_set_height(ui_VolumeSlider, 284);
    lv_obj_set_align(ui_VolumeSlider, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_VolumeSlider, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                       LV_OBJ_FLAG_SCROLL_MOMENTUM);     /// Flags
    lv_obj_set_style_radius(ui_VolumeSlider, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_VolumeSlider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeSlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_VolumeSlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_VolumeSlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_VolumeSlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_VolumeSlider,
                                                                                                   lv_obj_get_style_pad_right(ui_VolumeSlider, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_VolumeIcon = lv_image_create(ui_VolumeSlider);
    lv_image_set_src(ui_VolumeIcon, &ui_img_394312127);
    lv_obj_set_width(ui_VolumeIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_VolumeIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_VolumeIcon, 0);
    lv_obj_set_y(ui_VolumeIcon, 90);
    lv_obj_set_align(ui_VolumeIcon, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_VolumeIcon, LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SCROLLABLE);    /// Flags

    ui_Container6 = lv_obj_create(ui_ControlGroup);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, lv_pct(100));
    lv_obj_set_height(ui_Container6, lv_pct(24));
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 260);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Container6, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StyleButton = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_StyleButton, 120);
    lv_obj_set_height(ui_StyleButton, 120);
    lv_obj_set_x(ui_StyleButton, 0);
    lv_obj_set_y(ui_StyleButton, -10);
    lv_obj_set_align(ui_StyleButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_state(ui_StyleButton, LV_STATE_CHECKED);       /// States
    lv_obj_add_flag(ui_StyleButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE |
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_StyleButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StyleButton, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StyleButton, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StyleButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_StyleButton, &ui_img_848443434, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_StyleButton, 120, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_StyleButton, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_StyleButton, 200, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_FileButton = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_FileButton, 120);
    lv_obj_set_height(ui_FileButton, 120);
    lv_obj_set_x(ui_FileButton, 0);
    lv_obj_set_y(ui_FileButton, -10);
    lv_obj_set_align(ui_FileButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_FileButton, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE |
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_FileButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FileButton, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FileButton, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FileButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_FileButton, &ui_img_1479039066, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_FileButton, 120, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_FileButton, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_FileButton, 200, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Button15 = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_Button15, 120);
    lv_obj_set_height(ui_Button15, 120);
    lv_obj_set_x(ui_Button15, 0);
    lv_obj_set_y(ui_Button15, -10);
    lv_obj_set_align(ui_Button15, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Button15, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_OVERFLOW_VISIBLE |
                    LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Button15, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button15, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Button15, &ui_img_1978444994, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Button15, 120, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_Button15, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Button15, 200, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_InfoButton = lv_button_create(ui_Container6);
    lv_obj_set_width(ui_InfoButton, 120);
    lv_obj_set_height(ui_InfoButton, 120);
    lv_obj_set_x(ui_InfoButton, 0);
    lv_obj_set_y(ui_InfoButton, -10);
    lv_obj_set_align(ui_InfoButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_InfoButton, LV_OBJ_FLAG_OVERFLOW_VISIBLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_InfoButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_InfoButton, 120, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_InfoButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_InfoButton, &ui_img_1934789300, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_InfoButton, 120, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_InfoButton, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_InfoButton, 200, LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_add_event_cb(ui_WifiButton, ui_event_WifiButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BTButton, ui_event_BTButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_LastMusic, ui_event_LastMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pause, ui_event_Pause, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextMusic, ui_event_NextMusic, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MediaButton, ui_event_MediaButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_VolumeSlider, ui_event_VolumeSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StyleButton, ui_event_StyleButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_FileButton, ui_event_FileButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button15, ui_event_Button15, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_InfoButton, ui_event_InfoButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ControlPanel, ui_event_ControlPanel, LV_EVENT_ALL, NULL);
    uic_ControlPanel = ui_ControlPanel;
    uic_TimeButton11 = ui_TimeButton11;
    uic_Time = ui_Time;
    uic_ControlGroup = ui_ControlGroup;
    uic_WifiButton = ui_WifiButton;
    uic_WifSsidLabel = ui_WifSsidLabel;
    uic_WifiStatusLabel = ui_WifiStatusLabel;
    uic_WifiIcon64 = ui_WifiIcon64;
    uic_BTButton = ui_BTButton;
    uic_BTSsidLabel = ui_BTSsidLabel;
    uic_BTStatusLabel = ui_BTStatusLabel;
    uic_BTIcon64 = ui_BTIcon64;
    uic_MediaButton = ui_MediaButton;
    uic_MediaPlayerLabel = ui_MediaPlayerLabel;
    uic_MediaPic75 = ui_MediaPic75;
    uic_MediaName = ui_MediaName;
    uic_LastMusic = ui_LastMusic;
    uic_Pause = ui_Pause;
    uic_NextMusic = ui_NextMusic;
    uic_Container4 = ui_Container4;
    uic_BrightnessSlider = ui_BrightnessSlider;
    uic_BrightnessIcon = ui_BrightnessIcon;
    uic_VolumeSlider = ui_VolumeSlider;
    uic_VolumeIcon = ui_VolumeIcon;
    uic_StyleButton = ui_StyleButton;
    uic_FileButton = ui_FileButton;
    uic_InfoButton = ui_InfoButton;

}

void ui_ControlPanel_screen_destroy(void)
{
    if(ui_ControlPanel) lv_obj_del(ui_ControlPanel);

    // NULL screen variables
    uic_ControlPanel = NULL;
    ui_ControlPanel = NULL;
    ui_Status11 = NULL;
    uic_TimeButton11 = NULL;
    ui_TimeButton11 = NULL;
    uic_Time = NULL;
    ui_Time = NULL;
    uic_ControlGroup = NULL;
    ui_ControlGroup = NULL;
    ui_Container3 = NULL;
    uic_WifiButton = NULL;
    ui_WifiButton = NULL;
    uic_WifSsidLabel = NULL;
    ui_WifSsidLabel = NULL;
    uic_WifiStatusLabel = NULL;
    ui_WifiStatusLabel = NULL;
    uic_WifiIcon64 = NULL;
    ui_WifiIcon64 = NULL;
    uic_BTButton = NULL;
    ui_BTButton = NULL;
    uic_BTSsidLabel = NULL;
    ui_BTSsidLabel = NULL;
    uic_BTStatusLabel = NULL;
    ui_BTStatusLabel = NULL;
    uic_BTIcon64 = NULL;
    ui_BTIcon64 = NULL;
    ui_Container5 = NULL;
    uic_MediaButton = NULL;
    ui_MediaButton = NULL;
    uic_MediaPlayerLabel = NULL;
    ui_MediaPlayerLabel = NULL;
    uic_MediaPic75 = NULL;
    ui_MediaPic75 = NULL;
    uic_MediaName = NULL;
    ui_MediaName = NULL;
    uic_LastMusic = NULL;
    ui_LastMusic = NULL;
    uic_Pause = NULL;
    ui_Pause = NULL;
    uic_NextMusic = NULL;
    ui_NextMusic = NULL;
    uic_Container4 = NULL;
    ui_Container4 = NULL;
    uic_BrightnessSlider = NULL;
    ui_BrightnessSlider = NULL;
    uic_BrightnessIcon = NULL;
    ui_BrightnessIcon = NULL;
    uic_VolumeSlider = NULL;
    ui_VolumeSlider = NULL;
    uic_VolumeIcon = NULL;
    ui_VolumeIcon = NULL;
    ui_Container6 = NULL;
    uic_StyleButton = NULL;
    ui_StyleButton = NULL;
    uic_FileButton = NULL;
    ui_FileButton = NULL;
    ui_Button15 = NULL;
    uic_InfoButton = NULL;
    ui_InfoButton = NULL;

}
