// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern void ui_event_Home(lv_event_t * e);
extern lv_obj_t * ui_Home;
extern lv_obj_t * ui_Content7;
extern lv_obj_t * ui_TimeNow;
extern lv_obj_t * ui_MonthDay;
extern lv_obj_t * ui_Year;
extern lv_obj_t * ui_DayOfWeekLabel;
extern lv_obj_t * ui_TempNow;
extern lv_obj_t * ui_Humidity;
extern lv_obj_t * ui_WeatherIcon;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Home;
extern lv_obj_t * uic_TimeNow;
extern lv_obj_t * uic_MonthDay;
extern lv_obj_t * uic_Year;
extern lv_obj_t * uic_DayOfWeekLabel;
extern lv_obj_t * uic_TempNow;
extern lv_obj_t * uic_Humidity;
extern lv_obj_t * uic_WeatherIcon;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

