// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_WeatherIcon;
lv_obj_t * uic_Humidity;
lv_obj_t * uic_TempNow;
lv_obj_t * uic_DayOfWeekLabel;
lv_obj_t * uic_Year;
lv_obj_t * uic_MonthDay;
lv_obj_t * uic_TimeNow;
lv_obj_t * uic_Home;
lv_obj_t * ui_Home = NULL;
lv_obj_t * ui_Content7 = NULL;
lv_obj_t * ui_TimeNow = NULL;
lv_obj_t * ui_MonthDay = NULL;
lv_obj_t * ui_Year = NULL;
lv_obj_t * ui_DayOfWeekLabel = NULL;
lv_obj_t * ui_TempNow = NULL;
lv_obj_t * ui_Humidity = NULL;
lv_obj_t * ui_WeatherIcon = NULL;
// event funtions
void ui_event_Home(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_computerdashboard, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_computerdashboard_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Weather, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Weather_screen_init);
    }
}

// build funtions

void ui_Home_screen_init(void)
{
    ui_Home = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Home, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Home, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Home, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Content7 = lv_obj_create(ui_Home);
    lv_obj_remove_style_all(ui_Content7);
    lv_obj_set_width(ui_Content7, lv_pct(100));
    lv_obj_set_height(ui_Content7, lv_pct(100));
    lv_obj_set_align(ui_Content7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Content7, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_Content7, LV_DIR_VER);

    ui_TimeNow = lv_label_create(ui_Content7);
    lv_obj_set_width(ui_TimeNow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeNow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TimeNow, 0);
    lv_obj_set_y(ui_TimeNow, -50);
    lv_obj_set_align(ui_TimeNow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TimeNow, "00:00");
    ui_object_set_themeable_style_property(ui_TimeNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TimeNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(ui_TimeNow, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeNow, &ui_font_Pixel200, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MonthDay = lv_label_create(ui_Content7);
    lv_obj_set_width(ui_MonthDay, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MonthDay, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MonthDay, 311);
    lv_obj_set_y(ui_MonthDay, 75);
    lv_obj_set_align(ui_MonthDay, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MonthDay, "--  --");
    ui_object_set_themeable_style_property(ui_MonthDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_MonthDay, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(ui_MonthDay, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MonthDay, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Year = lv_label_create(ui_Content7);
    lv_obj_set_width(ui_Year, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Year, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Year, 173);
    lv_obj_set_y(ui_Year, 75);
    lv_obj_set_align(ui_Year, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Year, "----");
    ui_object_set_themeable_style_property(ui_Year, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Year, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_align(ui_Year, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Year, &lv_font_montserrat_46, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DayOfWeekLabel = lv_label_create(ui_Content7);
    lv_obj_set_width(ui_DayOfWeekLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DayOfWeekLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DayOfWeekLabel, 428);
    lv_obj_set_y(ui_DayOfWeekLabel, 75);
    lv_obj_set_align(ui_DayOfWeekLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DayOfWeekLabel, "---");
    ui_object_set_themeable_style_property(ui_DayOfWeekLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_DayOfWeekLabel, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_DayOfWeekLabel, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempNow = lv_label_create(ui_Home);
    lv_obj_set_width(ui_TempNow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempNow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempNow, -191);
    lv_obj_set_y(ui_TempNow, 478);
    lv_obj_set_align(ui_TempNow, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_TempNow, "--.-℃");
    ui_object_set_themeable_style_property(ui_TempNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TempNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_TempNow, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Humidity = lv_label_create(ui_Home);
    lv_obj_set_width(ui_Humidity, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity, -191);
    lv_obj_set_y(ui_Humidity, 530);
    lv_obj_set_align(ui_Humidity, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_Humidity, "Humidity:--%");
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Humidity, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_Humidity, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherIcon = lv_image_create(ui_Home);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 120
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 120
    lv_obj_set_x(ui_WeatherIcon, -139);
    lv_obj_set_y(ui_WeatherIcon, 159);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Home, ui_event_Home, LV_EVENT_ALL, NULL);
    uic_Home = ui_Home;
    uic_TimeNow = ui_TimeNow;
    uic_MonthDay = ui_MonthDay;
    uic_Year = ui_Year;
    uic_DayOfWeekLabel = ui_DayOfWeekLabel;
    uic_TempNow = ui_TempNow;
    uic_Humidity = ui_Humidity;
    uic_WeatherIcon = ui_WeatherIcon;

}

void ui_Home_screen_destroy(void)
{
    if(ui_Home) lv_obj_del(ui_Home);

    // NULL screen variables
    uic_Home = NULL;
    ui_Home = NULL;
    ui_Content7 = NULL;
    uic_TimeNow = NULL;
    ui_TimeNow = NULL;
    uic_MonthDay = NULL;
    ui_MonthDay = NULL;
    uic_Year = NULL;
    ui_Year = NULL;
    uic_DayOfWeekLabel = NULL;
    ui_DayOfWeekLabel = NULL;
    uic_TempNow = NULL;
    ui_TempNow = NULL;
    uic_Humidity = NULL;
    ui_Humidity = NULL;
    uic_WeatherIcon = NULL;
    ui_WeatherIcon = NULL;

}
