// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_MediaTimeLength;
lv_obj_t * uic_MediaTimeNow;
lv_obj_t * uic_lyrics;
lv_obj_t * uic_MusicProgress;
lv_obj_t * uic_PlayerLabel2;
lv_obj_t * uic_NextMusic2;
lv_obj_t * uic_Pause2;
lv_obj_t * uic_LastMusic2;
lv_obj_t * uic_Medianame2;
lv_obj_t * uic_MediaPic128;
lv_obj_t * uic_MediaPanel;
lv_obj_t * uic_Media;
lv_obj_t * ui_Media = NULL;
lv_obj_t * ui_MediaPanel = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_MediaPic128 = NULL;
lv_obj_t * ui_MediaName2 = NULL;
lv_obj_t * ui_LastMusic2 = NULL;
lv_obj_t * ui_Pause2 = NULL;
lv_obj_t * ui_NextMusic2 = NULL;
lv_obj_t * ui_PlayerLabel2 = NULL;
lv_obj_t * ui_MusicProgress = NULL;
lv_obj_t * ui_lyrics = NULL;
lv_obj_t * ui_MediaTimeNow = NULL;
lv_obj_t * ui_MediaTimeLength = NULL;
// event funtions
void ui_event_Media(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadMedia(e);
    }
}

void ui_event_LastMusic2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        LastMusic(e);
    }
}

void ui_event_Pause2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        PauseResume(e);
    }
}

void ui_event_NextMusic2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        NextMusic(e);
    }
}

// build funtions

void ui_Media_screen_init(void)
{
    ui_Media = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Media, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Media, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Media, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_MediaPanel = lv_obj_create(ui_Media);
    lv_obj_remove_style_all(ui_MediaPanel);
    lv_obj_set_width(ui_MediaPanel, lv_pct(80));
    lv_obj_set_height(ui_MediaPanel, lv_pct(80));
    lv_obj_set_align(ui_MediaPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MediaPanel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_MediaPanel);
    lv_obj_set_width(ui_Panel3, lv_pct(100));
    lv_obj_set_height(ui_Panel3, lv_pct(100));
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MediaPic128 = lv_image_create(ui_Panel3);
    lv_image_set_src(ui_MediaPic128, &ui_img_1368585089);
    lv_obj_set_width(ui_MediaPic128, 128);
    lv_obj_set_height(ui_MediaPic128, 128);
    lv_obj_set_x(ui_MediaPic128, -156);
    lv_obj_set_y(ui_MediaPic128, -161);
    lv_obj_set_align(ui_MediaPic128, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MediaPic128, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MediaPic128, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MediaName2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_MediaName2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediaName2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediaName2, 208);
    lv_obj_set_y(ui_MediaName2, -201);
    lv_obj_set_align(ui_MediaName2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_MediaName2, "Music");
    lv_obj_set_style_text_font(ui_MediaName2, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LastMusic2 = lv_imagebutton_create(ui_Panel3);
    lv_imagebutton_set_src(ui_LastMusic2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_862951715, NULL);
    lv_obj_set_width(ui_LastMusic2, 48);
    lv_obj_set_height(ui_LastMusic2, 48);
    lv_obj_set_x(ui_LastMusic2, -37);
    lv_obj_set_y(ui_LastMusic2, -120);
    lv_obj_set_align(ui_LastMusic2, LV_ALIGN_CENTER);

    ui_Pause2 = lv_imagebutton_create(ui_Panel3);
    lv_imagebutton_set_src(ui_Pause2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_933793681, NULL);
    lv_imagebutton_set_src(ui_Pause2, LV_IMAGEBUTTON_STATE_PRESSED, NULL, &ui_img_933793681, NULL);
    lv_imagebutton_set_src(ui_Pause2, LV_IMAGEBUTTON_STATE_CHECKED_PRESSED, NULL, &ui_img_59290064, NULL);
    lv_imagebutton_set_src(ui_Pause2, LV_IMAGEBUTTON_STATE_CHECKED_RELEASED, NULL, &ui_img_59290064, NULL);
    lv_obj_set_width(ui_Pause2, 48);
    lv_obj_set_height(ui_Pause2, 48);
    lv_obj_set_x(ui_Pause2, 77);
    lv_obj_set_y(ui_Pause2, -120);
    lv_obj_set_align(ui_Pause2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Pause2, LV_OBJ_FLAG_CHECKABLE);     /// Flags

    ui_NextMusic2 = lv_imagebutton_create(ui_Panel3);
    lv_imagebutton_set_src(ui_NextMusic2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_853450402, NULL);
    lv_obj_set_width(ui_NextMusic2, 48);
    lv_obj_set_height(ui_NextMusic2, 48);
    lv_obj_set_x(ui_NextMusic2, 192);
    lv_obj_set_y(ui_NextMusic2, -120);
    lv_obj_set_align(ui_NextMusic2, LV_ALIGN_CENTER);

    ui_PlayerLabel2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_PlayerLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PlayerLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PlayerLabel2, 212);
    lv_obj_set_y(ui_PlayerLabel2, -164);
    lv_obj_set_align(ui_PlayerLabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_PlayerLabel2, "Player");
    lv_obj_set_style_text_font(ui_PlayerLabel2, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MusicProgress = lv_slider_create(ui_Panel3);
    lv_slider_set_value(ui_MusicProgress, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_MusicProgress) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_MusicProgress, 0,
                                                                                                  LV_ANIM_OFF);
    lv_obj_set_height(ui_MusicProgress, 5);
    lv_obj_set_width(ui_MusicProgress, lv_pct(80));
    lv_obj_set_x(ui_MusicProgress, 0);
    lv_obj_set_y(ui_MusicProgress, -53);
    lv_obj_set_align(ui_MusicProgress, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_MusicProgress, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MusicProgress, lv_color_hex(0x7C7C7C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicProgress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MusicProgress, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicProgress, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_MusicProgress, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MusicProgress, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_MusicProgress, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_MusicProgress,
                                                                                                    lv_obj_get_style_pad_right(ui_MusicProgress, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_lyrics = lv_roller_create(ui_Panel3);
    lv_roller_set_options(ui_lyrics,
                          "Option 1\nOption 2\nOption 3\nOption 1\nOption 2\nOption 3\nOption 1\nOption 2\nOption 3", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_lyrics, 4, LV_ANIM_OFF);
    lv_obj_set_width(ui_lyrics, lv_pct(80));
    lv_obj_set_height(ui_lyrics, lv_pct(50));
    lv_obj_set_x(ui_lyrics, 0);
    lv_obj_set_y(ui_lyrics, 116);
    lv_obj_set_align(ui_lyrics, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_lyrics, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_color(ui_lyrics, lv_color_hex(0xA6A6A6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_lyrics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_lyrics, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_lyrics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lyrics, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lyrics, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_lyrics, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_lyrics, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_lyrics, lv_color_hex(0x676767), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_lyrics, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_MediaTimeNow = lv_label_create(ui_Media);
    lv_obj_set_width(ui_MediaTimeNow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediaTimeNow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediaTimeNow, 205);
    lv_obj_set_y(ui_MediaTimeNow, -25);
    lv_obj_set_align(ui_MediaTimeNow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MediaTimeNow, "2:30");

    ui_MediaTimeLength = lv_label_create(ui_Media);
    lv_obj_set_width(ui_MediaTimeLength, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MediaTimeLength, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MediaTimeLength, -205);
    lv_obj_set_y(ui_MediaTimeLength, -25);
    lv_obj_set_align(ui_MediaTimeLength, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MediaTimeLength, "0:00");
    lv_obj_remove_flag(ui_MediaTimeLength, LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags

    lv_obj_add_event_cb(ui_LastMusic2, ui_event_LastMusic2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Pause2, ui_event_Pause2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_NextMusic2, ui_event_NextMusic2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Media, ui_event_Media, LV_EVENT_ALL, NULL);
    uic_Media = ui_Media;
    uic_MediaPanel = ui_MediaPanel;
    uic_MediaPic128 = ui_MediaPic128;
    uic_Medianame2 = ui_MediaName2;
    uic_LastMusic2 = ui_LastMusic2;
    uic_Pause2 = ui_Pause2;
    uic_NextMusic2 = ui_NextMusic2;
    uic_PlayerLabel2 = ui_PlayerLabel2;
    uic_MusicProgress = ui_MusicProgress;
    uic_lyrics = ui_lyrics;
    uic_MediaTimeNow = ui_MediaTimeNow;
    uic_MediaTimeLength = ui_MediaTimeLength;

}

void ui_Media_screen_destroy(void)
{
    if(ui_Media) lv_obj_del(ui_Media);

    // NULL screen variables
    uic_Media = NULL;
    ui_Media = NULL;
    uic_MediaPanel = NULL;
    ui_MediaPanel = NULL;
    ui_Panel3 = NULL;
    uic_MediaPic128 = NULL;
    ui_MediaPic128 = NULL;
    uic_Medianame2 = NULL;
    ui_MediaName2 = NULL;
    uic_LastMusic2 = NULL;
    ui_LastMusic2 = NULL;
    uic_Pause2 = NULL;
    ui_Pause2 = NULL;
    uic_NextMusic2 = NULL;
    ui_NextMusic2 = NULL;
    uic_PlayerLabel2 = NULL;
    ui_PlayerLabel2 = NULL;
    uic_MusicProgress = NULL;
    ui_MusicProgress = NULL;
    uic_lyrics = NULL;
    ui_lyrics = NULL;
    uic_MediaTimeNow = NULL;
    ui_MediaTimeNow = NULL;
    uic_MediaTimeLength = NULL;
    ui_MediaTimeLength = NULL;

}
