// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_MEDIA_H
#define UI_MEDIA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Media
extern void ui_Media_screen_init(void);
extern void ui_Media_screen_destroy(void);
extern void ui_event_Media(lv_event_t * e);
extern lv_obj_t * ui_Media;
extern lv_obj_t * ui_MediaPanel;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_MediaPic128;
extern lv_obj_t * ui_MediaName2;
extern void ui_event_LastMusic2(lv_event_t * e);
extern lv_obj_t * ui_LastMusic2;
extern void ui_event_Pause2(lv_event_t * e);
extern lv_obj_t * ui_Pause2;
extern void ui_event_NextMusic2(lv_event_t * e);
extern lv_obj_t * ui_NextMusic2;
extern lv_obj_t * ui_PlayerLabel2;
extern lv_obj_t * ui_MusicProgress;
extern lv_obj_t * ui_lyrics;
extern lv_obj_t * ui_MediaTimeNow;
extern lv_obj_t * ui_MediaTimeLength;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Media;
extern lv_obj_t * uic_MediaPanel;
extern lv_obj_t * uic_MediaPic128;
extern lv_obj_t * uic_Medianame2;
extern lv_obj_t * uic_LastMusic2;
extern lv_obj_t * uic_Pause2;
extern lv_obj_t * uic_NextMusic2;
extern lv_obj_t * uic_PlayerLabel2;
extern lv_obj_t * uic_MusicProgress;
extern lv_obj_t * uic_lyrics;
extern lv_obj_t * uic_MediaTimeNow;
extern lv_obj_t * uic_MediaTimeLength;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

