// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_WEATHER_H
#define UI_WEATHER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Weather
extern void ui_Weather_screen_init(void);
extern void ui_Weather_screen_destroy(void);
extern void ui_event_Weather(lv_event_t * e);
extern lv_obj_t * ui_Weather;
extern lv_obj_t * ui_Status2;
extern lv_obj_t * ui_TimeButton2;
extern lv_obj_t * ui_Time2;
extern lv_obj_t * ui_Container16;
extern lv_obj_t * ui_WeatherNow;
extern lv_obj_t * ui_Location;
extern lv_obj_t * ui_label;
extern lv_obj_t * ui_city;
extern lv_obj_t * ui_updatetime;
extern lv_obj_t * ui_country;
extern lv_obj_t * ui_province;
extern lv_obj_t * ui_Alarm;
extern lv_obj_t * ui_AlarmIcon;
extern lv_obj_t * ui_Title;
extern lv_obj_t * ui_AlarmDate;
extern lv_obj_t * ui_Container21;
extern lv_obj_t * ui_Day;
extern lv_obj_t * ui_Nowweather1img;
extern lv_obj_t * ui_Nowweathertemp1;
extern lv_obj_t * ui_Nowweatherlabel1;
extern lv_obj_t * ui_Night;
extern lv_obj_t * ui_Nowweather2img;
extern lv_obj_t * ui_Nowweatherlabel2;
extern lv_obj_t * ui_Nowweathertemp2;
extern lv_obj_t * ui_Container22;
extern lv_obj_t * ui_Container24;
extern lv_obj_t * ui_WeatherDay1;
extern lv_obj_t * ui_WeatherDate1;
extern lv_obj_t * ui_Container17;
extern lv_obj_t * ui_Day1;
extern lv_obj_t * ui_weather1img1;
extern lv_obj_t * ui_weather1label1;
extern lv_obj_t * ui_weather1temp1;
extern lv_obj_t * ui_Night1;
extern lv_obj_t * ui_weather1img2;
extern lv_obj_t * ui_weather1label2;
extern lv_obj_t * ui_weather1temp2;
extern lv_obj_t * ui_Container19;
extern lv_obj_t * ui_WeatherDay2;
extern lv_obj_t * ui_WeatherDate2;
extern lv_obj_t * ui_Container20;
extern lv_obj_t * ui_Day2;
extern lv_obj_t * ui_weather2img1;
extern lv_obj_t * ui_weather2label1;
extern lv_obj_t * ui_weather2temp1;
extern lv_obj_t * ui_Night2;
extern lv_obj_t * ui_weather2img2;
extern lv_obj_t * ui_weather2label2;
extern lv_obj_t * ui_weather2temp2;
extern lv_obj_t * ui_Container23;
extern lv_obj_t * ui_WeatherDay3;
extern lv_obj_t * ui_WeatherDate3;
extern lv_obj_t * ui_Container25;
extern lv_obj_t * ui_Day3;
extern lv_obj_t * ui_weather3img1;
extern lv_obj_t * ui_weather3label1;
extern lv_obj_t * ui_weather3temp1;
extern lv_obj_t * ui_Night3;
extern lv_obj_t * ui_weather3img2;
extern lv_obj_t * ui_weather3label2;
extern lv_obj_t * ui_weather3temp2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Weather;
extern lv_obj_t * uic_TimeButton2;
extern lv_obj_t * uic_Time2;
extern lv_obj_t * uic_WeatherNow;
extern lv_obj_t * uic_Location;
extern lv_obj_t * uic_label;
extern lv_obj_t * uic_city;
extern lv_obj_t * uic_updatetime;
extern lv_obj_t * uic_country;
extern lv_obj_t * uic_province;
extern lv_obj_t * uic_Alarm;
extern lv_obj_t * uic_AlarmIcon;
extern lv_obj_t * uic_Title;
extern lv_obj_t * uic_AlarmDate;
extern lv_obj_t * uic_Day;
extern lv_obj_t * uic_Nowweather1img;
extern lv_obj_t * uic_Nowweathertemp1;
extern lv_obj_t * uic_Nowweatherlabel1;
extern lv_obj_t * uic_Night;
extern lv_obj_t * uic_Nowweather2img;
extern lv_obj_t * uic_Nowweatherlabel2;
extern lv_obj_t * uic_Nowweathertemp2;
extern lv_obj_t * uic_WeatherDay1;
extern lv_obj_t * uic_WeatherDate1;
extern lv_obj_t * uic_Day1;
extern lv_obj_t * uic_weather1img1;
extern lv_obj_t * uic_weather1label1;
extern lv_obj_t * uic_weather1temp1;
extern lv_obj_t * uic_Night1;
extern lv_obj_t * uic_weather1img2;
extern lv_obj_t * uic_weather1label2;
extern lv_obj_t * uic_weather1temp2;
extern lv_obj_t * uic_WeatherDate2;
extern lv_obj_t * uic_weather2img1;
extern lv_obj_t * uic_weather2label1;
extern lv_obj_t * uic_weather2temp1;
extern lv_obj_t * uic_weather2img2;
extern lv_obj_t * uic_weather2label2;
extern lv_obj_t * uic_weather2temp2;
extern lv_obj_t * uic_WeatherDate3;
extern lv_obj_t * uic_weather3img1;
extern lv_obj_t * uic_weather3label1;
extern lv_obj_t * uic_weather3temp1;
extern lv_obj_t * uic_weather3img2;
extern lv_obj_t * uic_weather3label2;
extern lv_obj_t * uic_weather3temp2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

