// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_weather3temp2;
lv_obj_t * uic_weather3label2;
lv_obj_t * uic_weather3img2;
lv_obj_t * uic_weather3temp1;
lv_obj_t * uic_weather3label1;
lv_obj_t * uic_weather3img1;
lv_obj_t * uic_WeatherDate3;
lv_obj_t * uic_weather2temp2;
lv_obj_t * uic_weather2label2;
lv_obj_t * uic_weather2img2;
lv_obj_t * uic_weather2temp1;
lv_obj_t * uic_weather2label1;
lv_obj_t * uic_weather2img1;
lv_obj_t * uic_WeatherDate2;
lv_obj_t * uic_weather1temp2;
lv_obj_t * uic_weather1label2;
lv_obj_t * uic_weather1img2;
lv_obj_t * uic_Night1;
lv_obj_t * uic_weather1temp1;
lv_obj_t * uic_weather1label1;
lv_obj_t * uic_weather1img1;
lv_obj_t * uic_Day1;
lv_obj_t * uic_WeatherDate1;
lv_obj_t * uic_WeatherDay1;
lv_obj_t * uic_Nowweathertemp2;
lv_obj_t * uic_Nowweatherlabel2;
lv_obj_t * uic_Nowweather2img;
lv_obj_t * uic_Night;
lv_obj_t * uic_Nowweatherlabel1;
lv_obj_t * uic_Nowweathertemp1;
lv_obj_t * uic_Nowweather1img;
lv_obj_t * uic_Day;
lv_obj_t * uic_AlarmDate;
lv_obj_t * uic_Title;
lv_obj_t * uic_AlarmIcon;
lv_obj_t * uic_Alarm;
lv_obj_t * uic_province;
lv_obj_t * uic_country;
lv_obj_t * uic_updatetime;
lv_obj_t * uic_city;
lv_obj_t * uic_label;
lv_obj_t * uic_Location;
lv_obj_t * uic_WeatherNow;
lv_obj_t * uic_Time2;
lv_obj_t * uic_TimeButton2;
lv_obj_t * uic_Weather;
lv_obj_t * ui_Weather = NULL;
lv_obj_t * ui_Status2 = NULL;
lv_obj_t * ui_TimeButton2 = NULL;
lv_obj_t * ui_Time2 = NULL;
lv_obj_t * ui_Container16 = NULL;
lv_obj_t * ui_WeatherNow = NULL;
lv_obj_t * ui_Location = NULL;
lv_obj_t * ui_label = NULL;
lv_obj_t * ui_city = NULL;
lv_obj_t * ui_updatetime = NULL;
lv_obj_t * ui_country = NULL;
lv_obj_t * ui_province = NULL;
lv_obj_t * ui_Alarm = NULL;
lv_obj_t * ui_AlarmIcon = NULL;
lv_obj_t * ui_Title = NULL;
lv_obj_t * ui_AlarmDate = NULL;
lv_obj_t * ui_Container21 = NULL;
lv_obj_t * ui_Day = NULL;
lv_obj_t * ui_Nowweather1img = NULL;
lv_obj_t * ui_Nowweathertemp1 = NULL;
lv_obj_t * ui_Nowweatherlabel1 = NULL;
lv_obj_t * ui_Night = NULL;
lv_obj_t * ui_Nowweather2img = NULL;
lv_obj_t * ui_Nowweatherlabel2 = NULL;
lv_obj_t * ui_Nowweathertemp2 = NULL;
lv_obj_t * ui_Container22 = NULL;
lv_obj_t * ui_Container24 = NULL;
lv_obj_t * ui_WeatherDay1 = NULL;
lv_obj_t * ui_WeatherDate1 = NULL;
lv_obj_t * ui_Container17 = NULL;
lv_obj_t * ui_Day1 = NULL;
lv_obj_t * ui_weather1img1 = NULL;
lv_obj_t * ui_weather1label1 = NULL;
lv_obj_t * ui_weather1temp1 = NULL;
lv_obj_t * ui_Night1 = NULL;
lv_obj_t * ui_weather1img2 = NULL;
lv_obj_t * ui_weather1label2 = NULL;
lv_obj_t * ui_weather1temp2 = NULL;
lv_obj_t * ui_Container19 = NULL;
lv_obj_t * ui_WeatherDay2 = NULL;
lv_obj_t * ui_WeatherDate2 = NULL;
lv_obj_t * ui_Container20 = NULL;
lv_obj_t * ui_Day2 = NULL;
lv_obj_t * ui_weather2img1 = NULL;
lv_obj_t * ui_weather2label1 = NULL;
lv_obj_t * ui_weather2temp1 = NULL;
lv_obj_t * ui_Night2 = NULL;
lv_obj_t * ui_weather2img2 = NULL;
lv_obj_t * ui_weather2label2 = NULL;
lv_obj_t * ui_weather2temp2 = NULL;
lv_obj_t * ui_Container23 = NULL;
lv_obj_t * ui_WeatherDay3 = NULL;
lv_obj_t * ui_WeatherDate3 = NULL;
lv_obj_t * ui_Container25 = NULL;
lv_obj_t * ui_Day3 = NULL;
lv_obj_t * ui_weather3img1 = NULL;
lv_obj_t * ui_weather3label1 = NULL;
lv_obj_t * ui_weather3temp1 = NULL;
lv_obj_t * ui_Night3 = NULL;
lv_obj_t * ui_weather3img2 = NULL;
lv_obj_t * ui_weather3label2 = NULL;
lv_obj_t * ui_weather3temp2 = NULL;
// event funtions
void ui_event_Weather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Home_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        LoadWeather(e);
    }
}

// build funtions

void ui_Weather_screen_init(void)
{
    ui_Weather = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Weather, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_Weather, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Status2 = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_Status2);
    lv_obj_set_width(ui_Status2, lv_pct(100));
    lv_obj_set_height(ui_Status2, lv_pct(5));
    lv_obj_set_align(ui_Status2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Status2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Status2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_Status2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);

    ui_TimeButton2 = lv_button_create(ui_Status2);
    lv_obj_set_width(ui_TimeButton2, lv_pct(30));
    lv_obj_set_height(ui_TimeButton2, lv_pct(80));
    lv_obj_set_x(ui_TimeButton2, 0);
    lv_obj_set_y(ui_TimeButton2, 3);
    lv_obj_set_align(ui_TimeButton2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_TimeButton2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_TimeButton2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_TimeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_TimeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);
    lv_obj_set_style_outline_color(ui_TimeButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_TimeButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_TimeButton2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_TimeButton2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_TimeButton2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_TimeButton2, LV_PART_MAIN | LV_STATE_PRESSED, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);

    ui_Time2 = lv_label_create(ui_TimeButton2);
    lv_obj_set_width(ui_Time2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time2, "--:--");
    ui_object_set_themeable_style_property(ui_Time2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Time2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_Time2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Time2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Time2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Time2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container16 = lv_obj_create(ui_Weather);
    lv_obj_remove_style_all(ui_Container16);
    lv_obj_set_width(ui_Container16, lv_pct(100));
    lv_obj_set_height(ui_Container16, lv_pct(95));
    lv_obj_set_x(ui_Container16, 0);
    lv_obj_set_y(ui_Container16, lv_pct(5));
    lv_obj_set_align(ui_Container16, LV_ALIGN_TOP_MID);
    lv_obj_set_flex_flow(ui_Container16, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags

    ui_WeatherNow = lv_obj_create(ui_Container16);
    lv_obj_set_width(ui_WeatherNow, lv_pct(95));
    lv_obj_set_height(ui_WeatherNow, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_x(ui_WeatherNow, 0);
    lv_obj_set_y(ui_WeatherNow, -2);
    lv_obj_set_align(ui_WeatherNow, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherNow, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherNow, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_WeatherNow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherNow, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WeatherNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_WeatherNow, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    lv_obj_set_style_border_width(ui_WeatherNow, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Location = lv_obj_create(ui_WeatherNow);
    lv_obj_remove_style_all(ui_Location);
    lv_obj_set_height(ui_Location, 50);
    lv_obj_set_width(ui_Location, lv_pct(100));
    lv_obj_set_x(ui_Location, 0);
    lv_obj_set_y(ui_Location, -120);
    lv_obj_set_align(ui_Location, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Location, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_label = lv_label_create(ui_Location);
    lv_obj_set_width(ui_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_label, 280);
    lv_obj_set_y(ui_label, 0);
    lv_obj_set_align(ui_label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_label, "更新日期:");
    ui_object_set_themeable_style_property(ui_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_label, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_label, &ui_font_Chinese24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_city = lv_label_create(ui_Location);
    lv_obj_set_width(ui_city, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_city, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_city, 160);
    lv_obj_set_y(ui_city, 0);
    lv_obj_set_align(ui_city, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_city, "--");
    ui_object_set_themeable_style_property(ui_city, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_city, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_city, &ui_font_Chinese24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_city, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_city, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_city, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);
    ui_object_set_themeable_style_property(ui_city, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_city, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Highlight);
    lv_obj_set_style_border_width(ui_city, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_updatetime = lv_label_create(ui_Location);
    lv_obj_set_width(ui_updatetime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_updatetime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_updatetime, 400);
    lv_obj_set_y(ui_updatetime, 0);
    lv_obj_set_align(ui_updatetime, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_updatetime, "-------- -- -- -- --:--:--");
    ui_object_set_themeable_style_property(ui_updatetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_updatetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_updatetime, &ui_font_Chinese24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_updatetime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_updatetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_updatetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);
    ui_object_set_themeable_style_property(ui_updatetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_updatetime, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Highlight);
    lv_obj_set_style_border_width(ui_updatetime, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_country = lv_label_create(ui_Location);
    lv_obj_set_width(ui_country, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_country, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_country, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_country, "中国");
    ui_object_set_themeable_style_property(ui_country, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_country, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_country, &ui_font_Chinese24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_country, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_country, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_country, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);
    ui_object_set_themeable_style_property(ui_country, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_country, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Highlight);
    lv_obj_set_style_border_width(ui_country, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_province = lv_label_create(ui_Location);
    lv_obj_set_width(ui_province, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_province, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_province, 80);
    lv_obj_set_y(ui_province, 0);
    lv_obj_set_align(ui_province, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_province, "--");
    ui_object_set_themeable_style_property(ui_province, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_province, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_province, &ui_font_Chinese24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_province, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_province, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_province, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Highlight);
    ui_object_set_themeable_style_property(ui_province, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR,
                                           _ui_theme_color_Highlight);
    ui_object_set_themeable_style_property(ui_province, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_Highlight);
    lv_obj_set_style_border_width(ui_province, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Alarm = lv_obj_create(ui_WeatherNow);
    lv_obj_remove_style_all(ui_Alarm);
    lv_obj_set_height(ui_Alarm, 100);
    lv_obj_set_width(ui_Alarm, lv_pct(100));
    lv_obj_set_align(ui_Alarm, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Alarm, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Alarm, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Alarm, lv_color_hex(0xF9FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Alarm, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmIcon = lv_image_create(ui_Alarm);
    lv_image_set_src(ui_AlarmIcon, &ui_img_1934789300);
    lv_obj_set_width(ui_AlarmIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmIcon, -260);
    lv_obj_set_y(ui_AlarmIcon, 1);
    lv_obj_set_align(ui_AlarmIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlarmIcon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AlarmIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Title = lv_label_create(ui_Alarm);
    lv_obj_set_width(ui_Title, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Title, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Title, 150);
    lv_obj_set_y(ui_Title, 20);
    lv_label_set_text(ui_Title, "------");
    ui_object_set_themeable_style_property(ui_Title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Title, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_Title, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmDate = lv_label_create(ui_Alarm);
    lv_obj_set_width(ui_AlarmDate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmDate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmDate, 150);
    lv_obj_set_y(ui_AlarmDate, 60);
    lv_label_set_text(ui_AlarmDate, "----/--/--");
    ui_object_set_themeable_style_property(ui_AlarmDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_AlarmDate, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_AlarmDate, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container21 = lv_obj_create(ui_WeatherNow);
    lv_obj_remove_style_all(ui_Container21);
    lv_obj_set_height(ui_Container21, 150);
    lv_obj_set_width(ui_Container21, lv_pct(100));
    lv_obj_set_align(ui_Container21, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Day = lv_obj_create(ui_Container21);
    lv_obj_remove_style_all(ui_Day);
    lv_obj_set_height(ui_Day, 140);
    lv_obj_set_width(ui_Day, lv_pct(48));
    lv_obj_set_align(ui_Day, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_Day, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Day, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Day, lv_color_hex(0xFF3600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Day, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nowweather1img = lv_image_create(ui_Day);
    lv_obj_set_width(ui_Nowweather1img, 120);
    lv_obj_set_height(ui_Nowweather1img, 120);
    lv_obj_set_x(ui_Nowweather1img, 10);
    lv_obj_set_y(ui_Nowweather1img, 0);
    lv_obj_set_align(ui_Nowweather1img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Nowweather1img, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Nowweather1img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Nowweathertemp1 = lv_label_create(ui_Day);
    lv_obj_set_width(ui_Nowweathertemp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Nowweathertemp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Nowweathertemp1, 100);
    lv_obj_set_y(ui_Nowweathertemp1, 0);
    lv_obj_set_align(ui_Nowweathertemp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Nowweathertemp1, "--");
    ui_object_set_themeable_style_property(ui_Nowweathertemp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Nowweathertemp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_Nowweathertemp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Nowweathertemp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Nowweathertemp1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Nowweathertemp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Nowweathertemp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Nowweathertemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Nowweathertemp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Nowweathertemp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Nowweathertemp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nowweatherlabel1 = lv_label_create(ui_Day);
    lv_obj_set_width(ui_Nowweatherlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Nowweatherlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Nowweatherlabel1, 10);
    lv_obj_set_y(ui_Nowweatherlabel1, 0);
    lv_obj_set_align(ui_Nowweatherlabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Nowweatherlabel1, "天气");
    ui_object_set_themeable_style_property(ui_Nowweatherlabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Nowweatherlabel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_Nowweatherlabel1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Night = lv_obj_create(ui_Container21);
    lv_obj_remove_style_all(ui_Night);
    lv_obj_set_height(ui_Night, 140);
    lv_obj_set_width(ui_Night, lv_pct(48));
    lv_obj_set_align(ui_Night, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_remove_flag(ui_Night, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Night, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Night, lv_color_hex(0x319EE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Night, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nowweather2img = lv_image_create(ui_Night);
    lv_obj_set_width(ui_Nowweather2img, 120);
    lv_obj_set_height(ui_Nowweather2img, 120);
    lv_obj_set_x(ui_Nowweather2img, 10);
    lv_obj_set_y(ui_Nowweather2img, 0);
    lv_obj_set_align(ui_Nowweather2img, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Nowweather2img, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Nowweather2img, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Nowweatherlabel2 = lv_label_create(ui_Night);
    lv_obj_set_width(ui_Nowweatherlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Nowweatherlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Nowweatherlabel2, 10);
    lv_obj_set_y(ui_Nowweatherlabel2, 0);
    lv_obj_set_align(ui_Nowweatherlabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Nowweatherlabel2, "天气");
    ui_object_set_themeable_style_property(ui_Nowweatherlabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Nowweatherlabel2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_Nowweatherlabel2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Nowweathertemp2 = lv_label_create(ui_Night);
    lv_obj_set_width(ui_Nowweathertemp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Nowweathertemp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Nowweathertemp2, 100);
    lv_obj_set_y(ui_Nowweathertemp2, 0);
    lv_obj_set_align(ui_Nowweathertemp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Nowweathertemp2, "--");
    ui_object_set_themeable_style_property(ui_Nowweathertemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_Nowweathertemp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_Nowweathertemp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_Nowweathertemp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Nowweathertemp2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Nowweathertemp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Nowweathertemp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Nowweathertemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Nowweathertemp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Nowweathertemp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Nowweathertemp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container22 = lv_obj_create(ui_Container21);
    lv_obj_remove_style_all(ui_Container22);
    lv_obj_set_width(ui_Container22, 100);
    lv_obj_set_height(ui_Container22, 50);
    lv_obj_set_x(ui_Container22, 3);
    lv_obj_set_y(ui_Container22, -6);
    lv_obj_set_align(ui_Container22, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container24 = lv_obj_create(ui_Container16);
    lv_obj_remove_style_all(ui_Container24);
    lv_obj_set_width(ui_Container24, lv_pct(95));
    lv_obj_set_height(ui_Container24, lv_pct(3));
    lv_obj_set_align(ui_Container24, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherDay1 = lv_obj_create(ui_Container16);
    lv_obj_set_width(ui_WeatherDay1, lv_pct(95));
    lv_obj_set_height(ui_WeatherDay1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherDay1, 0);
    lv_obj_set_y(ui_WeatherDay1, -2);
    lv_obj_set_align(ui_WeatherDay1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherDay1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherDay1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_WeatherDay1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherDay1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WeatherDay1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_WeatherDay1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    lv_obj_set_style_border_width(ui_WeatherDay1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDate1 = lv_label_create(ui_WeatherDay1);
    lv_obj_set_width(ui_WeatherDate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherDate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WeatherDate1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WeatherDate1, "----/--/--");
    ui_object_set_themeable_style_property(ui_WeatherDate1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_WeatherDate1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_WeatherDate1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container17 = lv_obj_create(ui_WeatherDay1);
    lv_obj_remove_style_all(ui_Container17);
    lv_obj_set_height(ui_Container17, 140);
    lv_obj_set_width(ui_Container17, lv_pct(100));
    lv_obj_set_align(ui_Container17, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Day1 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Day1);
    lv_obj_set_height(ui_Day1, 140);
    lv_obj_set_width(ui_Day1, lv_pct(48));
    lv_obj_set_align(ui_Day1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_Day1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Day1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Day1, lv_color_hex(0xFF3600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Day1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather1img1 = lv_image_create(ui_Day1);
    lv_obj_set_width(ui_weather1img1, 120);
    lv_obj_set_height(ui_weather1img1, 120);
    lv_obj_set_x(ui_weather1img1, 10);
    lv_obj_set_y(ui_weather1img1, 0);
    lv_obj_set_align(ui_weather1img1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weather1img1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather1img1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather1label1 = lv_label_create(ui_Day1);
    lv_obj_set_width(ui_weather1label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1label1, 10);
    lv_obj_set_y(ui_weather1label1, 3);
    lv_obj_set_align(ui_weather1label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1label1, "天气");
    ui_object_set_themeable_style_property(ui_weather1label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather1label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_weather1label1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather1temp1 = lv_label_create(ui_Day1);
    lv_obj_set_width(ui_weather1temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1temp1, 90);
    lv_obj_set_y(ui_weather1temp1, 0);
    lv_obj_set_align(ui_weather1temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1temp1, "--");
    ui_object_set_themeable_style_property(ui_weather1temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather1temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_weather1temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather1temp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather1temp1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weather1temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather1temp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather1temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather1temp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather1temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather1temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Night1 = lv_obj_create(ui_Container17);
    lv_obj_remove_style_all(ui_Night1);
    lv_obj_set_height(ui_Night1, 140);
    lv_obj_set_width(ui_Night1, lv_pct(48));
    lv_obj_set_align(ui_Night1, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Night1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Night1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Night1, lv_color_hex(0x319EE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Night1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather1img2 = lv_image_create(ui_Night1);
    lv_obj_set_width(ui_weather1img2, 120);
    lv_obj_set_height(ui_weather1img2, 120);
    lv_obj_set_x(ui_weather1img2, 10);
    lv_obj_set_y(ui_weather1img2, 0);
    lv_obj_set_align(ui_weather1img2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weather1img2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather1img2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather1label2 = lv_label_create(ui_Night1);
    lv_obj_set_width(ui_weather1label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1label2, 10);
    lv_obj_set_y(ui_weather1label2, 0);
    lv_obj_set_align(ui_weather1label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1label2, "天气");
    ui_object_set_themeable_style_property(ui_weather1label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather1label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_weather1label2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather1temp2 = lv_label_create(ui_Night1);
    lv_obj_set_width(ui_weather1temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1temp2, 100);
    lv_obj_set_y(ui_weather1temp2, 0);
    lv_obj_set_align(ui_weather1temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1temp2, "--");
    ui_object_set_themeable_style_property(ui_weather1temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather1temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_weather1temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather1temp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather1temp2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weather1temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather1temp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather1temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather1temp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather1temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather1temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container19 = lv_obj_create(ui_Container16);
    lv_obj_remove_style_all(ui_Container19);
    lv_obj_set_width(ui_Container19, lv_pct(95));
    lv_obj_set_height(ui_Container19, lv_pct(3));
    lv_obj_set_align(ui_Container19, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherDay2 = lv_obj_create(ui_Container16);
    lv_obj_set_width(ui_WeatherDay2, lv_pct(95));
    lv_obj_set_height(ui_WeatherDay2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherDay2, 0);
    lv_obj_set_y(ui_WeatherDay2, -2);
    lv_obj_set_align(ui_WeatherDay2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherDay2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherDay2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_WeatherDay2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherDay2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WeatherDay2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_WeatherDay2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    lv_obj_set_style_border_width(ui_WeatherDay2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDate2 = lv_label_create(ui_WeatherDay2);
    lv_obj_set_width(ui_WeatherDate2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherDate2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WeatherDate2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WeatherDate2, "----/--/--");
    ui_object_set_themeable_style_property(ui_WeatherDate2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_WeatherDate2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_WeatherDate2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container20 = lv_obj_create(ui_WeatherDay2);
    lv_obj_remove_style_all(ui_Container20);
    lv_obj_set_height(ui_Container20, 140);
    lv_obj_set_width(ui_Container20, lv_pct(100));
    lv_obj_set_align(ui_Container20, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Day2 = lv_obj_create(ui_Container20);
    lv_obj_remove_style_all(ui_Day2);
    lv_obj_set_height(ui_Day2, 140);
    lv_obj_set_width(ui_Day2, lv_pct(48));
    lv_obj_set_align(ui_Day2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_Day2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Day2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Day2, lv_color_hex(0xFF3600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Day2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather2img1 = lv_image_create(ui_Day2);
    lv_obj_set_width(ui_weather2img1, 120);
    lv_obj_set_height(ui_weather2img1, 120);
    lv_obj_set_x(ui_weather2img1, 10);
    lv_obj_set_y(ui_weather2img1, 0);
    lv_obj_set_align(ui_weather2img1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weather2img1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather2img1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather2label1 = lv_label_create(ui_Day2);
    lv_obj_set_width(ui_weather2label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather2label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather2label1, 10);
    lv_obj_set_y(ui_weather2label1, 3);
    lv_obj_set_align(ui_weather2label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather2label1, "天气");
    ui_object_set_themeable_style_property(ui_weather2label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather2label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_weather2label1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather2temp1 = lv_label_create(ui_Day2);
    lv_obj_set_width(ui_weather2temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather2temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather2temp1, 90);
    lv_obj_set_y(ui_weather2temp1, 0);
    lv_obj_set_align(ui_weather2temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather2temp1, "--");
    ui_object_set_themeable_style_property(ui_weather2temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather2temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_weather2temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather2temp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather2temp1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weather2temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather2temp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather2temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather2temp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather2temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather2temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Night2 = lv_obj_create(ui_Container20);
    lv_obj_remove_style_all(ui_Night2);
    lv_obj_set_height(ui_Night2, 140);
    lv_obj_set_width(ui_Night2, lv_pct(48));
    lv_obj_set_align(ui_Night2, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Night2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Night2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Night2, lv_color_hex(0x319EE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Night2, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather2img2 = lv_image_create(ui_Night2);
    lv_obj_set_width(ui_weather2img2, 120);
    lv_obj_set_height(ui_weather2img2, 120);
    lv_obj_set_x(ui_weather2img2, 10);
    lv_obj_set_y(ui_weather2img2, 0);
    lv_obj_set_align(ui_weather2img2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weather2img2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather2img2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather2label2 = lv_label_create(ui_Night2);
    lv_obj_set_width(ui_weather2label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather2label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather2label2, 10);
    lv_obj_set_y(ui_weather2label2, 0);
    lv_obj_set_align(ui_weather2label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather2label2, "天气");
    ui_object_set_themeable_style_property(ui_weather2label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather2label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_weather2label2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather2temp2 = lv_label_create(ui_Night2);
    lv_obj_set_width(ui_weather2temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather2temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather2temp2, 100);
    lv_obj_set_y(ui_weather2temp2, 0);
    lv_obj_set_align(ui_weather2temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather2temp2, "--");
    ui_object_set_themeable_style_property(ui_weather2temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather2temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_weather2temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather2temp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather2temp2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weather2temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather2temp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather2temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather2temp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather2temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather2temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container23 = lv_obj_create(ui_Container16);
    lv_obj_remove_style_all(ui_Container23);
    lv_obj_set_width(ui_Container23, lv_pct(95));
    lv_obj_set_height(ui_Container23, lv_pct(3));
    lv_obj_set_align(ui_Container23, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherDay3 = lv_obj_create(ui_Container16);
    lv_obj_set_width(ui_WeatherDay3, lv_pct(95));
    lv_obj_set_height(ui_WeatherDay3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherDay3, 0);
    lv_obj_set_y(ui_WeatherDay3, -2);
    lv_obj_set_align(ui_WeatherDay3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherDay3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherDay3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_WeatherDay3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherDay3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_WeatherDay3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_BackgroundButtom);
    ui_object_set_themeable_style_property(ui_WeatherDay3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_BackgroundButtom);
    lv_obj_set_style_border_width(ui_WeatherDay3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WeatherDate3 = lv_label_create(ui_WeatherDay3);
    lv_obj_set_width(ui_WeatherDate3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherDate3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WeatherDate3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_WeatherDate3, "----/--/--");
    ui_object_set_themeable_style_property(ui_WeatherDate3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_WeatherDate3, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_WeatherDate3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container25 = lv_obj_create(ui_WeatherDay3);
    lv_obj_remove_style_all(ui_Container25);
    lv_obj_set_height(ui_Container25, 140);
    lv_obj_set_width(ui_Container25, lv_pct(100));
    lv_obj_set_align(ui_Container25, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Day3 = lv_obj_create(ui_Container25);
    lv_obj_remove_style_all(ui_Day3);
    lv_obj_set_height(ui_Day3, 140);
    lv_obj_set_width(ui_Day3, lv_pct(48));
    lv_obj_set_align(ui_Day3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_remove_flag(ui_Day3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Day3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Day3, lv_color_hex(0xFF3600), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Day3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather3img1 = lv_image_create(ui_Day3);
    lv_obj_set_width(ui_weather3img1, 120);
    lv_obj_set_height(ui_weather3img1, 120);
    lv_obj_set_x(ui_weather3img1, 10);
    lv_obj_set_y(ui_weather3img1, 0);
    lv_obj_set_align(ui_weather3img1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weather3img1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather3img1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather3label1 = lv_label_create(ui_Day3);
    lv_obj_set_width(ui_weather3label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather3label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather3label1, 10);
    lv_obj_set_y(ui_weather3label1, 3);
    lv_obj_set_align(ui_weather3label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather3label1, "天气");
    ui_object_set_themeable_style_property(ui_weather3label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather3label1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_weather3label1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather3temp1 = lv_label_create(ui_Day3);
    lv_obj_set_width(ui_weather3temp1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather3temp1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather3temp1, 90);
    lv_obj_set_y(ui_weather3temp1, 0);
    lv_obj_set_align(ui_weather3temp1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather3temp1, "--");
    ui_object_set_themeable_style_property(ui_weather3temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather3temp1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_weather3temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather3temp1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather3temp1, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weather3temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather3temp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather3temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather3temp1, lv_color_hex(0xE26100), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather3temp1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather3temp1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Night3 = lv_obj_create(ui_Container25);
    lv_obj_remove_style_all(ui_Night3);
    lv_obj_set_height(ui_Night3, 140);
    lv_obj_set_width(ui_Night3, lv_pct(48));
    lv_obj_set_align(ui_Night3, LV_ALIGN_RIGHT_MID);
    lv_obj_remove_flag(ui_Night3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Night3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Night3, lv_color_hex(0x319EE1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Night3, 50, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather3img2 = lv_image_create(ui_Night3);
    lv_obj_set_width(ui_weather3img2, 120);
    lv_obj_set_height(ui_weather3img2, 120);
    lv_obj_set_x(ui_weather3img2, 10);
    lv_obj_set_y(ui_weather3img2, 0);
    lv_obj_set_align(ui_weather3img2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_weather3img2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_weather3img2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_weather3label2 = lv_label_create(ui_Night3);
    lv_obj_set_width(ui_weather3label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather3label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather3label2, 10);
    lv_obj_set_y(ui_weather3label2, 0);
    lv_obj_set_align(ui_weather3label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather3label2, "天气");
    ui_object_set_themeable_style_property(ui_weather3label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather3label2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_font(ui_weather3label2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_weather3temp2 = lv_label_create(ui_Night3);
    lv_obj_set_width(ui_weather3temp2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather3temp2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather3temp2, 100);
    lv_obj_set_y(ui_weather3temp2, 0);
    lv_obj_set_align(ui_weather3temp2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather3temp2, "--");
    ui_object_set_themeable_style_property(ui_weather3temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_Text);
    ui_object_set_themeable_style_property(ui_weather3temp2, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_Text);
    lv_obj_set_style_text_letter_space(ui_weather3temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_weather3temp2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_weather3temp2, &ui_font_weatherfont28, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_weather3temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_weather3temp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather3temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_weather3temp2, lv_color_hex(0x4DA9EB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_weather3temp2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_weather3temp2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Weather, ui_event_Weather, LV_EVENT_ALL, NULL);
    uic_Weather = ui_Weather;
    uic_TimeButton2 = ui_TimeButton2;
    uic_Time2 = ui_Time2;
    uic_WeatherNow = ui_WeatherNow;
    uic_Location = ui_Location;
    uic_label = ui_label;
    uic_city = ui_city;
    uic_updatetime = ui_updatetime;
    uic_country = ui_country;
    uic_province = ui_province;
    uic_Alarm = ui_Alarm;
    uic_AlarmIcon = ui_AlarmIcon;
    uic_Title = ui_Title;
    uic_AlarmDate = ui_AlarmDate;
    uic_Day = ui_Day;
    uic_Nowweather1img = ui_Nowweather1img;
    uic_Nowweathertemp1 = ui_Nowweathertemp1;
    uic_Nowweatherlabel1 = ui_Nowweatherlabel1;
    uic_Night = ui_Night;
    uic_Nowweather2img = ui_Nowweather2img;
    uic_Nowweatherlabel2 = ui_Nowweatherlabel2;
    uic_Nowweathertemp2 = ui_Nowweathertemp2;
    uic_WeatherDay1 = ui_WeatherDay1;
    uic_WeatherDate1 = ui_WeatherDate1;
    uic_Day1 = ui_Day1;
    uic_weather1img1 = ui_weather1img1;
    uic_weather1label1 = ui_weather1label1;
    uic_weather1temp1 = ui_weather1temp1;
    uic_Night1 = ui_Night1;
    uic_weather1img2 = ui_weather1img2;
    uic_weather1label2 = ui_weather1label2;
    uic_weather1temp2 = ui_weather1temp2;
    uic_WeatherDate2 = ui_WeatherDate2;
    uic_weather2img1 = ui_weather2img1;
    uic_weather2label1 = ui_weather2label1;
    uic_weather2temp1 = ui_weather2temp1;
    uic_weather2img2 = ui_weather2img2;
    uic_weather2label2 = ui_weather2label2;
    uic_weather2temp2 = ui_weather2temp2;
    uic_WeatherDate3 = ui_WeatherDate3;
    uic_weather3img1 = ui_weather3img1;
    uic_weather3label1 = ui_weather3label1;
    uic_weather3temp1 = ui_weather3temp1;
    uic_weather3img2 = ui_weather3img2;
    uic_weather3label2 = ui_weather3label2;
    uic_weather3temp2 = ui_weather3temp2;

}

void ui_Weather_screen_destroy(void)
{
    if(ui_Weather) lv_obj_del(ui_Weather);

    // NULL screen variables
    uic_Weather = NULL;
    ui_Weather = NULL;
    ui_Status2 = NULL;
    uic_TimeButton2 = NULL;
    ui_TimeButton2 = NULL;
    uic_Time2 = NULL;
    ui_Time2 = NULL;
    ui_Container16 = NULL;
    uic_WeatherNow = NULL;
    ui_WeatherNow = NULL;
    uic_Location = NULL;
    ui_Location = NULL;
    uic_label = NULL;
    ui_label = NULL;
    uic_city = NULL;
    ui_city = NULL;
    uic_updatetime = NULL;
    ui_updatetime = NULL;
    uic_country = NULL;
    ui_country = NULL;
    uic_province = NULL;
    ui_province = NULL;
    uic_Alarm = NULL;
    ui_Alarm = NULL;
    uic_AlarmIcon = NULL;
    ui_AlarmIcon = NULL;
    uic_Title = NULL;
    ui_Title = NULL;
    uic_AlarmDate = NULL;
    ui_AlarmDate = NULL;
    ui_Container21 = NULL;
    uic_Day = NULL;
    ui_Day = NULL;
    uic_Nowweather1img = NULL;
    ui_Nowweather1img = NULL;
    uic_Nowweathertemp1 = NULL;
    ui_Nowweathertemp1 = NULL;
    uic_Nowweatherlabel1 = NULL;
    ui_Nowweatherlabel1 = NULL;
    uic_Night = NULL;
    ui_Night = NULL;
    uic_Nowweather2img = NULL;
    ui_Nowweather2img = NULL;
    uic_Nowweatherlabel2 = NULL;
    ui_Nowweatherlabel2 = NULL;
    uic_Nowweathertemp2 = NULL;
    ui_Nowweathertemp2 = NULL;
    ui_Container22 = NULL;
    ui_Container24 = NULL;
    uic_WeatherDay1 = NULL;
    ui_WeatherDay1 = NULL;
    uic_WeatherDate1 = NULL;
    ui_WeatherDate1 = NULL;
    ui_Container17 = NULL;
    uic_Day1 = NULL;
    ui_Day1 = NULL;
    uic_weather1img1 = NULL;
    ui_weather1img1 = NULL;
    uic_weather1label1 = NULL;
    ui_weather1label1 = NULL;
    uic_weather1temp1 = NULL;
    ui_weather1temp1 = NULL;
    uic_Night1 = NULL;
    ui_Night1 = NULL;
    uic_weather1img2 = NULL;
    ui_weather1img2 = NULL;
    uic_weather1label2 = NULL;
    ui_weather1label2 = NULL;
    uic_weather1temp2 = NULL;
    ui_weather1temp2 = NULL;
    ui_Container19 = NULL;
    ui_WeatherDay2 = NULL;
    uic_WeatherDate2 = NULL;
    ui_WeatherDate2 = NULL;
    ui_Container20 = NULL;
    ui_Day2 = NULL;
    uic_weather2img1 = NULL;
    ui_weather2img1 = NULL;
    uic_weather2label1 = NULL;
    ui_weather2label1 = NULL;
    uic_weather2temp1 = NULL;
    ui_weather2temp1 = NULL;
    ui_Night2 = NULL;
    uic_weather2img2 = NULL;
    ui_weather2img2 = NULL;
    uic_weather2label2 = NULL;
    ui_weather2label2 = NULL;
    uic_weather2temp2 = NULL;
    ui_weather2temp2 = NULL;
    ui_Container23 = NULL;
    ui_WeatherDay3 = NULL;
    uic_WeatherDate3 = NULL;
    ui_WeatherDate3 = NULL;
    ui_Container25 = NULL;
    ui_Day3 = NULL;
    uic_weather3img1 = NULL;
    ui_weather3img1 = NULL;
    uic_weather3label1 = NULL;
    ui_weather3label1 = NULL;
    uic_weather3temp1 = NULL;
    ui_weather3temp1 = NULL;
    ui_Night3 = NULL;
    uic_weather3img2 = NULL;
    ui_weather3img2 = NULL;
    uic_weather3label2 = NULL;
    ui_weather3label2 = NULL;
    uic_weather3temp2 = NULL;
    ui_weather3temp2 = NULL;

}
