// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_WIFIPWD_H
#define UI_WIFIPWD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiPwd
extern void ui_WifiPwd_screen_init(void);
extern void ui_WifiPwd_screen_destroy(void);
extern void ui_event_WifiPwd(lv_event_t * e);
extern lv_obj_t * ui_WifiPwd;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_SSIDlabel;
extern lv_obj_t * ui_wifipwdarea;
extern lv_obj_t * ui_Container12;
extern void ui_event_CancelButton(lv_event_t * e);
extern lv_obj_t * ui_CancelButton;
extern lv_obj_t * ui_CancelLabel;
extern void ui_event_ConnectButton(lv_event_t * e);
extern lv_obj_t * ui_ConnectButton;
extern lv_obj_t * ui_ConnectLabel;
extern lv_obj_t * ui_Keyboard;
extern lv_obj_t * ui_Spinner;
// CUSTOM VARIABLES
extern lv_obj_t * uic_WifiPwd;
extern lv_obj_t * uic_SSIDlabel;
extern lv_obj_t * uic_wifipwdarea;
extern lv_obj_t * uic_CancelLabel;
extern lv_obj_t * uic_ConnectButton;
extern lv_obj_t * uic_ConnectLabel;
extern lv_obj_t * uic_Keyboard;
extern lv_obj_t * uic_Spinner;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

