// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#ifndef UI_WIFICHOOSE_H
#define UI_WIFICHOOSE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiChoose
extern void ui_WifiChoose_screen_init(void);
extern void ui_WifiChoose_screen_destroy(void);
extern void ui_event_WifiChoose(lv_event_t * e);
extern lv_obj_t * ui_WifiChoose;
extern lv_obj_t * ui_WifiGroup1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label10;
extern void ui_event_wifiSwitch(lv_event_t * e);
extern lv_obj_t * ui_wifiSwitch;
extern lv_obj_t * ui_Wifilist;
extern lv_obj_t * ui_Currentwifi;
extern lv_obj_t * ui_WifiIcon32;
extern lv_obj_t * ui_Currentwifilabel;
extern lv_obj_t * ui_wifistatus;
extern lv_obj_t * ui_Container18;
extern lv_obj_t * ui_Label29;
extern void ui_event_Wifilist1(lv_event_t * e);
extern lv_obj_t * ui_Wifilist1;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Wifilistlabel1;
extern lv_obj_t * ui_wifiBlock1;
extern void ui_event_Wifilist2(lv_event_t * e);
extern lv_obj_t * ui_Wifilist2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Wifilistlabel2;
extern lv_obj_t * ui_wifiBlock2;
extern void ui_event_Wifilist3(lv_event_t * e);
extern lv_obj_t * ui_Wifilist3;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Wifilistlabel3;
extern lv_obj_t * ui_wifiBlock3;
extern void ui_event_Wifilist4(lv_event_t * e);
extern lv_obj_t * ui_Wifilist4;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Wifilistlabel4;
extern lv_obj_t * ui_wifiBlock4;
extern void ui_event_Wifilist5(lv_event_t * e);
extern lv_obj_t * ui_Wifilist5;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Wifilistlabel5;
extern lv_obj_t * ui_wifiBlock5;
extern void ui_event_Wifilist6(lv_event_t * e);
extern lv_obj_t * ui_Wifilist6;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Wifilistlabel6;
extern lv_obj_t * ui_wifiBlock6;
extern void ui_event_Wifilist7(lv_event_t * e);
extern lv_obj_t * ui_Wifilist7;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Wifilistlabel7;
extern lv_obj_t * ui_wifiBlock7;
extern void ui_event_Wifilist8(lv_event_t * e);
extern lv_obj_t * ui_Wifilist8;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Wifilistlabel8;
extern lv_obj_t * ui_wifiBlock8;
extern void ui_event_Wifilist9(lv_event_t * e);
extern lv_obj_t * ui_Wifilist9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Wifilistlabel9;
extern lv_obj_t * ui_wifiBlock9;
// CUSTOM VARIABLES
extern lv_obj_t * uic_wifiSwitch;
extern lv_obj_t * uic_Wifilist;
extern lv_obj_t * uic_WifiIcon32;
extern lv_obj_t * uic_Currentwifilabel;
extern lv_obj_t * uic_wifistatus;
extern lv_obj_t * uic_Wifilist1;
extern lv_obj_t * uic_Wifilistlabel1;
extern lv_obj_t * uic_wifiBlock1;
extern lv_obj_t * uic_Wifilist2;
extern lv_obj_t * uic_Wifilist3;
extern lv_obj_t * uic_Wifilist4;
extern lv_obj_t * uic_Wifilist5;
extern lv_obj_t * uic_Wifilist6;
extern lv_obj_t * uic_Wifilist7;
extern lv_obj_t * uic_Wifilist8;
extern lv_obj_t * uic_Wifilist9;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

