// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_Wifilist9;
lv_obj_t * uic_Wifilist8;
lv_obj_t * uic_Wifilist7;
lv_obj_t * uic_Wifilist6;
lv_obj_t * uic_Wifilist5;
lv_obj_t * uic_Wifilist4;
lv_obj_t * uic_Wifilist3;
lv_obj_t * uic_Wifilist2;
lv_obj_t * uic_wifiBlock1;
lv_obj_t * uic_Wifilistlabel1;
lv_obj_t * uic_Wifilist1;
lv_obj_t * uic_wifistatus;
lv_obj_t * uic_Currentwifilabel;
lv_obj_t * uic_WifiIcon32;
lv_obj_t * uic_Wifilist;
lv_obj_t * uic_wifiSwitch;
lv_obj_t * ui_WifiChoose = NULL;
lv_obj_t * ui_WifiGroup1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_wifiSwitch = NULL;
lv_obj_t * ui_Wifilist = NULL;
lv_obj_t * ui_Currentwifi = NULL;
lv_obj_t * ui_WifiIcon32 = NULL;
lv_obj_t * ui_Currentwifilabel = NULL;
lv_obj_t * ui_wifistatus = NULL;
lv_obj_t * ui_Container18 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Wifilist1 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Wifilistlabel1 = NULL;
lv_obj_t * ui_wifiBlock1 = NULL;
lv_obj_t * ui_Wifilist2 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Wifilistlabel2 = NULL;
lv_obj_t * ui_wifiBlock2 = NULL;
lv_obj_t * ui_Wifilist3 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Wifilistlabel3 = NULL;
lv_obj_t * ui_wifiBlock3 = NULL;
lv_obj_t * ui_Wifilist4 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Wifilistlabel4 = NULL;
lv_obj_t * ui_wifiBlock4 = NULL;
lv_obj_t * ui_Wifilist5 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Wifilistlabel5 = NULL;
lv_obj_t * ui_wifiBlock5 = NULL;
lv_obj_t * ui_Wifilist6 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Wifilistlabel6 = NULL;
lv_obj_t * ui_wifiBlock6 = NULL;
lv_obj_t * ui_Wifilist7 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Wifilistlabel7 = NULL;
lv_obj_t * ui_wifiBlock7 = NULL;
lv_obj_t * ui_Wifilist8 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Wifilistlabel8 = NULL;
lv_obj_t * ui_wifiBlock8 = NULL;
lv_obj_t * ui_Wifilist9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Wifilistlabel9 = NULL;
lv_obj_t * ui_wifiBlock9 = NULL;
// event funtions
void ui_event_WifiChoose(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_ControlPanel, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ControlPanel_screen_init);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        wifi_check(e);
    }
}

void ui_event_wifiSwitch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        wifi_scan(e);
        wifi_on(e);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        wifi_off(e);
    }
}

void ui_event_Wifilist1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect1(e);
    }
}

void ui_event_Wifilist2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect2(e);
    }
}

void ui_event_Wifilist3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect3(e);
    }
}

void ui_event_Wifilist4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect4(e);
    }
}

void ui_event_Wifilist5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect5(e);
    }
}

void ui_event_Wifilist6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect6(e);
    }
}

void ui_event_Wifilist7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect7(e);
    }
}

void ui_event_Wifilist8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect8(e);
    }
}

void ui_event_Wifilist9(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiPwd, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiPwd_screen_init);
        WifiConnect9(e);
    }
}

// build funtions

void ui_WifiChoose_screen_init(void)
{
    ui_WifiChoose = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiChoose, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_WifiChoose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_WifiChoose, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_WifiGroup1 = lv_obj_create(ui_WifiChoose);
    lv_obj_remove_style_all(ui_WifiGroup1);
    lv_obj_set_width(ui_WifiGroup1, lv_pct(80));
    lv_obj_set_height(ui_WifiGroup1, lv_pct(80));
    lv_obj_set_align(ui_WifiGroup1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WifiGroup1, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_WifiGroup1);
    lv_obj_set_width(ui_Panel2, lv_pct(100));
    lv_obj_set_height(ui_Panel2, lv_pct(100));
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -1);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x676767), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -164);
    lv_obj_set_y(ui_Label10, -210);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "WLAN");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_42, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiSwitch = lv_switch_create(ui_Panel2);
    lv_obj_set_width(ui_wifiSwitch, 90);
    lv_obj_set_height(ui_wifiSwitch, 45);
    lv_obj_set_x(ui_wifiSwitch, 178);
    lv_obj_set_y(ui_wifiSwitch, -208);
    lv_obj_set_align(ui_wifiSwitch, LV_ALIGN_CENTER);

    ui_Wifilist = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Wifilist);
    lv_obj_set_width(ui_Wifilist, lv_pct(90));
    lv_obj_set_height(ui_Wifilist, lv_pct(73));
    lv_obj_set_x(ui_Wifilist, 0);
    lv_obj_set_y(ui_Wifilist, 34);
    lv_obj_set_align(ui_Wifilist, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Wifilist, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Wifilist, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_remove_flag(ui_Wifilist, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_Currentwifi = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Currentwifi, 75);
    lv_obj_set_width(ui_Currentwifi, lv_pct(100));
    lv_obj_set_align(ui_Currentwifi, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Currentwifi, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Currentwifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Currentwifi, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WifiIcon32 = lv_image_create(ui_Currentwifi);
    lv_image_set_src(ui_WifiIcon32, &ui_img_502970333);
    lv_obj_set_width(ui_WifiIcon32, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WifiIcon32, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_WifiIcon32, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_WifiIcon32, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WifiIcon32, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Currentwifilabel = lv_label_create(ui_Currentwifi);
    lv_obj_set_width(ui_Currentwifilabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Currentwifilabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Currentwifilabel, 45);
    lv_obj_set_y(ui_Currentwifilabel, -10);
    lv_obj_set_align(ui_Currentwifilabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Currentwifilabel, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Currentwifilabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifistatus = lv_label_create(ui_Currentwifi);
    lv_obj_set_width(ui_wifistatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifistatus, 47);
    lv_obj_set_y(ui_wifistatus, 11);
    lv_obj_set_align(ui_wifistatus, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_wifistatus, "Connected");
    lv_obj_set_style_text_font(ui_wifistatus, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container18 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_Container18);
    lv_obj_set_width(ui_Container18, 100);
    lv_obj_set_height(ui_Container18, 10);
    lv_obj_set_align(ui_Container18, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label29 = lv_label_create(ui_Wifilist);
    lv_obj_set_height(ui_Label29, 30);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(ui_Label29, 19);
    lv_obj_set_y(ui_Label29, -55);
    lv_obj_set_align(ui_Label29, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label29, "Avaliable");
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Wifilist1 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist1, 75);
    lv_obj_set_width(ui_Wifilist1, lv_pct(100));
    lv_obj_set_align(ui_Wifilist1, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist1, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist1, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist1, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_image_create(ui_Wifilist1);
    lv_image_set_src(ui_Image7, &ui_img_502970333);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel1 = lv_label_create(ui_Wifilist1);
    lv_obj_set_width(ui_Wifilistlabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel1, 45);
    lv_obj_set_y(ui_Wifilistlabel1, 0);
    lv_obj_set_align(ui_Wifilistlabel1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel1, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock1 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock1);
    lv_obj_set_width(ui_wifiBlock1, 100);
    lv_obj_set_height(ui_wifiBlock1, 10);
    lv_obj_set_align(ui_wifiBlock1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist2 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist2, 75);
    lv_obj_set_width(ui_Wifilist2, lv_pct(100));
    lv_obj_set_align(ui_Wifilist2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist2, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist2, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist2, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Wifilist2);
    lv_image_set_src(ui_Image1, &ui_img_502970333);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel2 = lv_label_create(ui_Wifilist2);
    lv_obj_set_width(ui_Wifilistlabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel2, 45);
    lv_obj_set_y(ui_Wifilistlabel2, 0);
    lv_obj_set_align(ui_Wifilistlabel2, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel2, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock2 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock2);
    lv_obj_set_width(ui_wifiBlock2, 100);
    lv_obj_set_height(ui_wifiBlock2, 10);
    lv_obj_set_align(ui_wifiBlock2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist3 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist3, 75);
    lv_obj_set_width(ui_Wifilist3, lv_pct(100));
    lv_obj_set_align(ui_Wifilist3, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist3, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist3, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist3, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_image_create(ui_Wifilist3);
    lv_image_set_src(ui_Image2, &ui_img_502970333);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel3 = lv_label_create(ui_Wifilist3);
    lv_obj_set_width(ui_Wifilistlabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel3, 45);
    lv_obj_set_y(ui_Wifilistlabel3, 0);
    lv_obj_set_align(ui_Wifilistlabel3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel3, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock3 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock3);
    lv_obj_set_width(ui_wifiBlock3, 100);
    lv_obj_set_height(ui_wifiBlock3, 10);
    lv_obj_set_align(ui_wifiBlock3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist4 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist4, 75);
    lv_obj_set_width(ui_Wifilist4, lv_pct(100));
    lv_obj_set_align(ui_Wifilist4, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist4, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist4, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist4, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_image_create(ui_Wifilist4);
    lv_image_set_src(ui_Image3, &ui_img_502970333);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel4 = lv_label_create(ui_Wifilist4);
    lv_obj_set_width(ui_Wifilistlabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel4, 45);
    lv_obj_set_y(ui_Wifilistlabel4, 0);
    lv_obj_set_align(ui_Wifilistlabel4, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel4, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock4 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock4);
    lv_obj_set_width(ui_wifiBlock4, 100);
    lv_obj_set_height(ui_wifiBlock4, 10);
    lv_obj_set_align(ui_wifiBlock4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist5 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist5, 75);
    lv_obj_set_width(ui_Wifilist5, lv_pct(100));
    lv_obj_set_align(ui_Wifilist5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist5, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist5, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist5, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist5, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_image_create(ui_Wifilist5);
    lv_image_set_src(ui_Image4, &ui_img_502970333);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel5 = lv_label_create(ui_Wifilist5);
    lv_obj_set_width(ui_Wifilistlabel5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel5, 45);
    lv_obj_set_y(ui_Wifilistlabel5, 0);
    lv_obj_set_align(ui_Wifilistlabel5, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel5, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel5, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock5 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock5);
    lv_obj_set_width(ui_wifiBlock5, 100);
    lv_obj_set_height(ui_wifiBlock5, 10);
    lv_obj_set_align(ui_wifiBlock5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist6 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist6, 75);
    lv_obj_set_width(ui_Wifilist6, lv_pct(100));
    lv_obj_set_align(ui_Wifilist6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist6, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist6, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist6, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist6, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_image_create(ui_Wifilist6);
    lv_image_set_src(ui_Image5, &ui_img_502970333);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel6 = lv_label_create(ui_Wifilist6);
    lv_obj_set_width(ui_Wifilistlabel6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel6, 45);
    lv_obj_set_y(ui_Wifilistlabel6, 0);
    lv_obj_set_align(ui_Wifilistlabel6, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel6, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock6 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock6);
    lv_obj_set_width(ui_wifiBlock6, 100);
    lv_obj_set_height(ui_wifiBlock6, 10);
    lv_obj_set_align(ui_wifiBlock6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist7 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist7, 75);
    lv_obj_set_width(ui_Wifilist7, lv_pct(100));
    lv_obj_set_align(ui_Wifilist7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist7, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist7, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist7, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist7, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_Wifilist7);
    lv_image_set_src(ui_Image8, &ui_img_502970333);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image8, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel7 = lv_label_create(ui_Wifilist7);
    lv_obj_set_width(ui_Wifilistlabel7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel7, 45);
    lv_obj_set_y(ui_Wifilistlabel7, 0);
    lv_obj_set_align(ui_Wifilistlabel7, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel7, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel7, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock7 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock7);
    lv_obj_set_width(ui_wifiBlock7, 100);
    lv_obj_set_height(ui_wifiBlock7, 10);
    lv_obj_set_align(ui_wifiBlock7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist8 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist8, 75);
    lv_obj_set_width(ui_Wifilist8, lv_pct(100));
    lv_obj_set_align(ui_Wifilist8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist8, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist8, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist8, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist8, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image9 = lv_image_create(ui_Wifilist8);
    lv_image_set_src(ui_Image9, &ui_img_502970333);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image9, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel8 = lv_label_create(ui_Wifilist8);
    lv_obj_set_width(ui_Wifilistlabel8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel8, 45);
    lv_obj_set_y(ui_Wifilistlabel8, 0);
    lv_obj_set_align(ui_Wifilistlabel8, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel8, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock8 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock8);
    lv_obj_set_width(ui_wifiBlock8, 100);
    lv_obj_set_height(ui_wifiBlock8, 10);
    lv_obj_set_align(ui_wifiBlock8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilist9 = lv_button_create(ui_Wifilist);
    lv_obj_set_height(ui_Wifilist9, 75);
    lv_obj_set_width(ui_Wifilist9, lv_pct(100));
    lv_obj_set_align(ui_Wifilist9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Wifilist9, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Wifilist9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Wifilist9, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Wifilist9, lv_color_hex(0x757575), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifilist9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_clip_corner(ui_Wifilist9, true, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_image_create(ui_Wifilist9);
    lv_image_set_src(ui_Image10, &ui_img_502970333);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image10, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Wifilistlabel9 = lv_label_create(ui_Wifilist9);
    lv_obj_set_width(ui_Wifilistlabel9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Wifilistlabel9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Wifilistlabel9, 45);
    lv_obj_set_y(ui_Wifilistlabel9, 0);
    lv_obj_set_align(ui_Wifilistlabel9, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Wifilistlabel9, "HUAWEI-213");
    lv_obj_set_style_text_font(ui_Wifilistlabel9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiBlock9 = lv_obj_create(ui_Wifilist);
    lv_obj_remove_style_all(ui_wifiBlock9);
    lv_obj_set_width(ui_wifiBlock9, 100);
    lv_obj_set_height(ui_wifiBlock9, 10);
    lv_obj_set_align(ui_wifiBlock9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiBlock9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_wifiSwitch, ui_event_wifiSwitch, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist1, ui_event_Wifilist1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist2, ui_event_Wifilist2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist3, ui_event_Wifilist3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist4, ui_event_Wifilist4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist5, ui_event_Wifilist5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist6, ui_event_Wifilist6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist7, ui_event_Wifilist7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist8, ui_event_Wifilist8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Wifilist9, ui_event_Wifilist9, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WifiChoose, ui_event_WifiChoose, LV_EVENT_ALL, NULL);
    uic_wifiSwitch = ui_wifiSwitch;
    uic_Wifilist = ui_Wifilist;
    uic_WifiIcon32 = ui_WifiIcon32;
    uic_Currentwifilabel = ui_Currentwifilabel;
    uic_wifistatus = ui_wifistatus;
    uic_Wifilist1 = ui_Wifilist1;
    uic_Wifilistlabel1 = ui_Wifilistlabel1;
    uic_wifiBlock1 = ui_wifiBlock1;
    uic_Wifilist2 = ui_Wifilist2;
    uic_Wifilist3 = ui_Wifilist3;
    uic_Wifilist4 = ui_Wifilist4;
    uic_Wifilist5 = ui_Wifilist5;
    uic_Wifilist6 = ui_Wifilist6;
    uic_Wifilist7 = ui_Wifilist7;
    uic_Wifilist8 = ui_Wifilist8;
    uic_Wifilist9 = ui_Wifilist9;

}

void ui_WifiChoose_screen_destroy(void)
{
    if(ui_WifiChoose) lv_obj_del(ui_WifiChoose);

    // NULL screen variables
    ui_WifiChoose = NULL;
    ui_WifiGroup1 = NULL;
    ui_Panel2 = NULL;
    ui_Label10 = NULL;
    uic_wifiSwitch = NULL;
    ui_wifiSwitch = NULL;
    uic_Wifilist = NULL;
    ui_Wifilist = NULL;
    ui_Currentwifi = NULL;
    uic_WifiIcon32 = NULL;
    ui_WifiIcon32 = NULL;
    uic_Currentwifilabel = NULL;
    ui_Currentwifilabel = NULL;
    uic_wifistatus = NULL;
    ui_wifistatus = NULL;
    ui_Container18 = NULL;
    ui_Label29 = NULL;
    uic_Wifilist1 = NULL;
    ui_Wifilist1 = NULL;
    ui_Image7 = NULL;
    uic_Wifilistlabel1 = NULL;
    ui_Wifilistlabel1 = NULL;
    uic_wifiBlock1 = NULL;
    ui_wifiBlock1 = NULL;
    uic_Wifilist2 = NULL;
    ui_Wifilist2 = NULL;
    ui_Image1 = NULL;
    ui_Wifilistlabel2 = NULL;
    ui_wifiBlock2 = NULL;
    uic_Wifilist3 = NULL;
    ui_Wifilist3 = NULL;
    ui_Image2 = NULL;
    ui_Wifilistlabel3 = NULL;
    ui_wifiBlock3 = NULL;
    uic_Wifilist4 = NULL;
    ui_Wifilist4 = NULL;
    ui_Image3 = NULL;
    ui_Wifilistlabel4 = NULL;
    ui_wifiBlock4 = NULL;
    uic_Wifilist5 = NULL;
    ui_Wifilist5 = NULL;
    ui_Image4 = NULL;
    ui_Wifilistlabel5 = NULL;
    ui_wifiBlock5 = NULL;
    uic_Wifilist6 = NULL;
    ui_Wifilist6 = NULL;
    ui_Image5 = NULL;
    ui_Wifilistlabel6 = NULL;
    ui_wifiBlock6 = NULL;
    uic_Wifilist7 = NULL;
    ui_Wifilist7 = NULL;
    ui_Image8 = NULL;
    ui_Wifilistlabel7 = NULL;
    ui_wifiBlock7 = NULL;
    uic_Wifilist8 = NULL;
    ui_Wifilist8 = NULL;
    ui_Image9 = NULL;
    ui_Wifilistlabel8 = NULL;
    ui_wifiBlock8 = NULL;
    uic_Wifilist9 = NULL;
    ui_Wifilist9 = NULL;
    ui_Image10 = NULL;
    ui_Wifilistlabel9 = NULL;
    ui_wifiBlock9 = NULL;

}
