// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: ComputerDashboard

#include "../ui.h"

lv_obj_t * uic_Spinner;
lv_obj_t * uic_Keyboard;
lv_obj_t * uic_ConnectLabel;
lv_obj_t * uic_ConnectButton;
lv_obj_t * uic_CancelLabel;
lv_obj_t * uic_wifipwdarea;
lv_obj_t * uic_SSIDlabel;
lv_obj_t * uic_WifiPwd;
lv_obj_t * ui_WifiPwd = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_SSIDlabel = NULL;
lv_obj_t * ui_wifipwdarea = NULL;
lv_obj_t * ui_Container12 = NULL;
lv_obj_t * ui_CancelButton = NULL;
lv_obj_t * ui_CancelLabel = NULL;
lv_obj_t * ui_ConnectButton = NULL;
lv_obj_t * ui_ConnectLabel = NULL;
lv_obj_t * ui_Keyboard = NULL;
lv_obj_t * ui_Spinner = NULL;
// event funtions
void ui_event_WifiPwd(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WifiChoose, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiChoose_screen_init);
        fade_Animation(ui_Panel4, 0);
        popoutkeyboard_Animation(ui_Keyboard, 0);
    }
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        popkeyboard_Animation(ui_Keyboard, 0);
        pop_Animation(ui_Panel4, 0);
        _ui_flag_modify(ui_Panel4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_CancelButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        fade_Animation(ui_Panel4, 0);
        popoutkeyboard_Animation(ui_Keyboard, 0);
        _ui_screen_change(&ui_WifiChoose, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiChoose_screen_init);
    }
}

void ui_event_ConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        ConnectWifi(e);
        _ui_screen_change(&ui_WifiChoose, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_WifiChoose_screen_init);
    }
}

// build funtions

void ui_WifiPwd_screen_init(void)
{
    ui_WifiPwd = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WifiPwd, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_WifiPwd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Background);
    ui_object_set_themeable_style_property(ui_WifiPwd, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Background);

    ui_Panel4 = lv_obj_create(ui_WifiPwd);
    lv_obj_set_height(ui_Panel4, 300);
    lv_obj_set_width(ui_Panel4, lv_pct(80));
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -170);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel4, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SSIDlabel = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_SSIDlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SSIDlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SSIDlabel, 0);
    lv_obj_set_y(ui_SSIDlabel, 15);
    lv_obj_set_align(ui_SSIDlabel, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_SSIDlabel, "HUAWEI-213");
    lv_obj_set_style_text_color(ui_SSIDlabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SSIDlabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SSIDlabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifipwdarea = lv_textarea_create(ui_Panel4);
    lv_obj_set_width(ui_wifipwdarea, lv_pct(95));
    lv_obj_set_height(ui_wifipwdarea, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_wifipwdarea, 0);
    lv_obj_set_y(ui_wifipwdarea, -10);
    lv_obj_set_align(ui_wifipwdarea, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_wifipwdarea, "Password");
    lv_textarea_set_one_line(ui_wifipwdarea, true);
    lv_textarea_set_password_mode(ui_wifipwdarea, true);
    lv_obj_add_state(ui_wifipwdarea, LV_STATE_FOCUSED);       /// States
    lv_obj_set_style_text_color(ui_wifipwdarea, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_wifipwdarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_wifipwdarea, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wifipwdarea, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_wifipwdarea, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_wifipwdarea, lv_color_hex(0xD9D9D9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifipwdarea, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifipwdarea, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_wifipwdarea, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_opa(ui_wifipwdarea, 255, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_border_width(ui_wifipwdarea, 4, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_Container12 = lv_obj_create(ui_Panel4);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_height(ui_Container12, 80);
    lv_obj_set_width(ui_Container12, lv_pct(95));
    lv_obj_set_x(ui_Container12, 0);
    lv_obj_set_y(ui_Container12, -10);
    lv_obj_set_align(ui_Container12, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CancelButton = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_CancelButton, lv_pct(45));
    lv_obj_set_height(ui_CancelButton, lv_pct(90));
    lv_obj_set_align(ui_CancelButton, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_CancelButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_CancelButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_CancelButton, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CancelButton, lv_color_hex(0xD3D3D3), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CancelButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CancelLabel = lv_label_create(ui_CancelButton);
    lv_obj_set_width(ui_CancelLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CancelLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CancelLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CancelLabel, "Cancel");
    lv_obj_remove_flag(ui_CancelLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_CancelLabel, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_CancelLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CancelLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectButton = lv_button_create(ui_Container12);
    lv_obj_set_width(ui_ConnectButton, lv_pct(45));
    lv_obj_set_height(ui_ConnectButton, lv_pct(90));
    lv_obj_set_align(ui_ConnectButton, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_ConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConnectButton, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ConnectButton, lv_color_hex(0x007EC9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectLabel = lv_label_create(ui_ConnectButton);
    lv_obj_set_width(ui_ConnectLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ConnectLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectLabel, "Connect");
    lv_obj_remove_flag(ui_ConnectLabel, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE);      /// Flags
    lv_obj_set_style_text_color(ui_ConnectLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectLabel, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard = lv_keyboard_create(ui_WifiPwd);
    lv_obj_set_width(ui_Keyboard, lv_pct(100));
    lv_obj_set_height(ui_Keyboard, lv_pct(40));
    lv_obj_set_x(ui_Keyboard, 0);
    lv_obj_set_y(ui_Keyboard, 510);
    lv_obj_set_align(ui_Keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner = lv_spinner_create(ui_WifiPwd);
    //lv_spinner_set_anim_params(ui_Spinner, 1000, 90);
    lv_obj_set_width(ui_Spinner, 50);
    lv_obj_set_height(ui_Spinner, 50);
    lv_obj_set_x(ui_Spinner, 143);
    lv_obj_set_y(ui_Spinner, -89);
    lv_obj_set_align(ui_Spinner, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_Spinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_color(ui_Spinner, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Spinner, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_CancelButton, ui_event_CancelButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ConnectButton, ui_event_ConnectButton, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard, ui_wifipwdarea);
    lv_obj_add_event_cb(ui_WifiPwd, ui_event_WifiPwd, LV_EVENT_ALL, NULL);
    uic_WifiPwd = ui_WifiPwd;
    uic_SSIDlabel = ui_SSIDlabel;
    uic_wifipwdarea = ui_wifipwdarea;
    uic_CancelLabel = ui_CancelLabel;
    uic_ConnectButton = ui_ConnectButton;
    uic_ConnectLabel = ui_ConnectLabel;
    uic_Keyboard = ui_Keyboard;
    uic_Spinner = ui_Spinner;

}

void ui_WifiPwd_screen_destroy(void)
{
    if(ui_WifiPwd) lv_obj_del(ui_WifiPwd);

    // NULL screen variables
    uic_WifiPwd = NULL;
    ui_WifiPwd = NULL;
    ui_Panel4 = NULL;
    uic_SSIDlabel = NULL;
    ui_SSIDlabel = NULL;
    uic_wifipwdarea = NULL;
    ui_wifipwdarea = NULL;
    ui_Container12 = NULL;
    ui_CancelButton = NULL;
    uic_CancelLabel = NULL;
    ui_CancelLabel = NULL;
    uic_ConnectButton = NULL;
    ui_ConnectButton = NULL;
    uic_ConnectLabel = NULL;
    ui_ConnectLabel = NULL;
    uic_Keyboard = NULL;
    ui_Keyboard = NULL;
    uic_Spinner = NULL;
    ui_Spinner = NULL;

}
