[book]
title = "ESP Serial Slave Link Documentation"
language = "en"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/espressif/idf-extra-components/tree/master/esp_serial_slave_link"
edit-url-template = "https://github.com/espressif/idf-extra-components/edit/master/esp_serial_slave_link/docs/{path}"
