repos:
  - repo: local
    hooks:
    - id: version-checker
      name: ESP-Hosted Version Checker
      entry: tools/check_fw_versions.py
      language: python
      args: [ "--update" ]
      always_run: true
      pass_filenames: false
  - repo: https://github.com/espressif/check-copyright/
    rev: v1.1.1
    hooks:
      - id: check-copyright
        args: ['--config', 'tools/check_copyright_config.yaml']
